In [1]:
import os
from ftplib import FTP
from pathlib import Path
import zipfile
import polars as pl

In [6]:
df = pl.read_csv('data/raw/tbEstabelecimento202201.csv', separator=';', encoding='latin1')

In [ ]:
codigos = [
    '530170', '530040', '530060', '530180',
    '530050', '530130', '530090', '530070',
    '530080', '530120', '530135', '530100',
    '530020', '530150'
]

df = df.with_columns([
    pl.col('CO_ESTADO_GESTOR').cast(pl.Utf8),
    pl.col('CO_MUNICIPIO_GESTOR').cast(pl.Utf8)
])

df = df.with_columns(
    pl.when(pl.col('CO_MUNICIPIO_GESTOR').is_in(codigos))
    .then(pl.lit('530010'))
    .otherwise(pl.col('CO_MUNICIPIO_GESTOR'))
    .alias('CO_MUNICIPIO_GESTOR')
)

df.filter(
    pl.col('CO_ESTADO_GESTOR') == '53'
)['CO_MUNICIPIO_GESTOR'].unique()

shape: (15,)
Series: 'CO_MUNICIPIO_GESTOR' [str]
[
	"530080"
	"530100"
	"530090"
	"530180"
	"530020"
	…
	"530130"
	"530170"
	"530135"
	"530120"
	"530050"
]

In [5]:
dir = os.listdir('data/ibge')

for files in dir:
    df = pl.read_excel(f'data/ibge/{files}')
    print(f'File: {files}')
    print(f'Number of rows: {df.shape[0]}')
    print(f'Number of columns: {df.shape[1]}')
    print(f'Columns: {df.columns}')
    print(f'First 3 rows:')
    print(df.head(3))
    print(f'Last 3 rows:')
    print(df.tail(3))
    print(f'Number of missing values: {df.null_count().sum()}')
    print(f'Number of duplicates: {df.is_duplicated().sum()}')
    print(f'Number of unique values: {df.n_unique()}')

File: tabela10056 - taxa_frequencia_escolar.xlsx
Number of rows: 5570
Number of columns: 9
Columns: ['codigo', 'nome', 'total', '0_3_anos', '4_5_anos', '6_14_anos', '15_17_anos', '18_24_anos', '25_mais']
First 3 rows:
shape: (3, 9)
┌─────────┬─────────────────┬───────┬──────────┬───┬───────────┬────────────┬────────────┬─────────┐
│ codigo  ┆ nome            ┆ total ┆ 0_3_anos ┆ … ┆ 6_14_anos ┆ 15_17_anos ┆ 18_24_anos ┆ 25_mais │
│ ---     ┆ ---             ┆ ---   ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---     │
│ str     ┆ str             ┆ f64   ┆ str      ┆   ┆ f64       ┆ f64        ┆ f64        ┆ f64     │
╞═════════╪═════════════════╪═══════╪══════════╪═══╪═══════════╪════════════╪════════════╪═════════╡
│ 1100015 ┆ Alta Floresta   ┆ 36.32 ┆ 10.95    ┆ … ┆ 97.44     ┆ 84.23      ┆ 34.23      ┆ 22.33   │
│         ┆ D'Oeste (RO)    ┆       ┆          ┆   ┆           ┆            ┆            ┆         │
│ 1100023 ┆ Ariquemes (RO)  ┆ 26.96 ┆ 16.61    ┆ … ┆ 98.12     ┆ 79.66      ┆ 28.59      ┆ 6.38    │
│ 1100031 ┆ Cabixi (RO)     ┆ 24.15 ┆ 18.12    ┆ … ┆ 99.55     ┆ 91.12      ┆ 18.93      ┆ 3.09    │
└─────────┴─────────────────┴───────┴──────────┴───┴───────────┴────────────┴────────────┴─────────┘
Last 3 rows:
shape: (3, 9)
┌─────────┬─────────────────┬───────┬──────────┬───┬───────────┬────────────┬────────────┬─────────┐
│ codigo  ┆ nome            ┆ total ┆ 0_3_anos ┆ … ┆ 6_14_anos ┆ 15_17_anos ┆ 18_24_anos ┆ 25_mais │
│ ---     ┆ ---             ┆ ---   ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---     │
│ str     ┆ str             ┆ f64   ┆ str      ┆   ┆ f64       ┆ f64        ┆ f64        ┆ f64     │
╞═════════╪═════════════════╪═══════╪══════════╪═══╪═══════════╪════════════╪════════════╪═════════╡
│ 5222203 ┆ Vila Boa (GO)   ┆ 26.79 ┆ 23.09    ┆ … ┆ 100.0     ┆ 91.29      ┆ 11.84      ┆ 2.61    │
│ 5222302 ┆ Vila Propício   ┆ 24.64 ┆ 37.74    ┆ … ┆ 100.0     ┆ 90.93      ┆ 17.24      ┆ 2.28    │
│         ┆ (GO)            ┆       ┆          ┆   ┆           ┆            ┆            ┆         │
│ 5300108 ┆ Brasília (DF)   ┆ 28.76 ┆ 30.52    ┆ … ┆ 98.96     ┆ 89.49      ┆ 36.83      ┆ 8.48    │
└─────────┴─────────────────┴───────┴──────────┴───┴───────────┴────────────┴────────────┴─────────┘
Number of missing values: shape: (1, 9)
┌────────┬──────┬───────┬──────────┬───┬───────────┬────────────┬────────────┬─────────┐
│ codigo ┆ nome ┆ total ┆ 0_3_anos ┆ … ┆ 6_14_anos ┆ 15_17_anos ┆ 18_24_anos ┆ 25_mais │
│ ---    ┆ ---  ┆ ---   ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---     │
│ u32    ┆ u32  ┆ u32   ┆ u32      ┆   ┆ u32       ┆ u32        ┆ u32        ┆ u32     │
╞════════╪══════╪═══════╪══════════╪═══╪═══════════╪════════════╪════════════╪═════════╡
│ 0      ┆ 0    ┆ 0     ┆ 0        ┆ … ┆ 0         ┆ 0          ┆ 0          ┆ 0       │
└────────┴──────┴───────┴──────────┴───┴───────────┴────────────┴────────────┴─────────┘
Number of duplicates: 0
Number of unique values: 5570
File: tabela10061 - taxa_populacao_nivel_instrucao.xlsx
Number of rows: 5570
Number of columns: 6
Columns: ['codigo', 'nome', 'sem_instrucao_fundamental_incompleto', 'fundamental_completo_medio_incompleto', 'medio_completo_superior_incompleto', 'superior_completo']
First 3 rows:
shape: (3, 6)
┌─────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ codigo  ┆ nome            ┆ sem_instrucao_f ┆ fundamental_com ┆ medio_completo_ ┆ superior_compl │
│ ---     ┆ ---             ┆ undamental_inco ┆ pleto_medio_inc ┆ superior_incomp ┆ eto            │
│ str     ┆ str             ┆ …               ┆ …               ┆ …               ┆ ---            │
│         ┆                 ┆ ---             ┆ ---             ┆ ---             ┆ f64            │
│         ┆                 ┆ f64             ┆ f64             ┆ f64             ┆                │
╞═════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ 1100015 ┆ Alta Floresta   ┆ 54.47           ┆ 16.97           ┆ 19.09           ┆ 9.47           │
│         ┆ D'Oeste (RO)    ┆                 ┆                 ┆                 ┆                │
│ 1100023 ┆ Ariquemes (RO)  ┆ 37.21           ┆ 15.99           ┆ 32.33           ┆ 14.46          │
│ 1100031 ┆ Cabixi (RO)     ┆ 53.41           ┆ 10.24           ┆ 25.81           ┆ 10.54          │
└─────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┘
Last 3 rows:
shape: (3, 6)
┌─────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ codigo  ┆ nome            ┆ sem_instrucao_f ┆ fundamental_com ┆ medio_completo_ ┆ superior_compl │
│ ---     ┆ ---             ┆ undamental_inco ┆ pleto_medio_inc ┆ superior_incomp ┆ eto            │
│ str     ┆ str             ┆ …               ┆ …               ┆ …               ┆ ---            │
│         ┆                 ┆ ---             ┆ ---             ┆ ---             ┆ f64            │
│         ┆                 ┆ f64             ┆ f64             ┆ f64             ┆                │
╞═════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ 5222203 ┆ Vila Boa (GO)   ┆ 47.32           ┆ 15.57           ┆ 31.88           ┆ 5.22           │
│ 5222302 ┆ Vila Propício   ┆ 50.9            ┆ 16.07           ┆ 24.95           ┆ 8.05           │
│         ┆ (GO)            ┆                 ┆                 ┆                 ┆                │
│ 5300108 ┆ Brasília (DF)   ┆ 17.52           ┆ 11.93           ┆ 37.38           ┆ 33.16          │
└─────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┘
Number of missing values: shape: (1, 6)
┌────────┬──────┬────────────────────┬────────────────────┬────────────────────┬───────────────────┐
│ codigo ┆ nome ┆ sem_instrucao_fund ┆ fundamental_comple ┆ medio_completo_sup ┆ superior_completo │
│ ---    ┆ ---  ┆ amental_inco…      ┆ to_medio_inc…      ┆ erior_incomp…      ┆ ---               │
│ u32    ┆ u32  ┆ ---                ┆ ---                ┆ ---                ┆ u32               │
│        ┆      ┆ u32                ┆ u32                ┆ u32                ┆                   │
╞════════╪══════╪════════════════════╪════════════════════╪════════════════════╪═══════════════════╡
│ 0      ┆ 0    ┆ 0                  ┆ 0                  ┆ 0                  ┆ 0                 │
└────────┴──────┴────────────────────┴────────────────────┴────────────────────┴───────────────────┘
Number of duplicates: 0
Number of unique values: 5570
File: tabela10062 - anos_de_estudo.xlsx
Number of rows: 5571
Number of columns: 7
Columns: ['codigo', 'nome', 'total', '11_14', '15_17', '18_24', '25_mais']
First 3 rows:
shape: (3, 7)
┌─────────┬────────────────────────────┬───────┬───────┬───────┬───────┬─────────┐
│ codigo  ┆ nome                       ┆ total ┆ 11_14 ┆ 15_17 ┆ 18_24 ┆ 25_mais │
│ ---     ┆ ---                        ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---     │
│ str     ┆ str                        ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64     │
╞═════════╪════════════════════════════╪═══════╪═══════╪═══════╪═══════╪═════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 7.1   ┆ 6.3   ┆ 8.3   ┆ 10.4  ┆ 6.5     │
│ 1100023 ┆ Ariquemes (RO)             ┆ 8.9   ┆ 6.3   ┆ 8.9   ┆ 11.2  ┆ 8.7     │
│ 1100031 ┆ Cabixi (RO)                ┆ 7.3   ┆ 6.1   ┆ 8.5   ┆ 10.9  ┆ 7.0     │
└─────────┴────────────────────────────┴───────┴───────┴───────┴───────┴─────────┘
Last 3 rows:
shape: (3, 7)
┌─────────────────────────────────┬────────────────────┬───────┬───────┬───────┬───────┬─────────┐
│ codigo                          ┆ nome               ┆ total ┆ 11_14 ┆ 15_17 ┆ 18_24 ┆ 25_mais │
│ ---                             ┆ ---                ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---     │
│ str                             ┆ str                ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64     │
╞═════════════════════════════════╪════════════════════╪═══════╪═══════╪═══════╪═══════╪═════════╡
│ 5222302                         ┆ Vila Propício (GO) ┆ 7.6   ┆ 6.2   ┆ 9.5   ┆ 11.4  ┆ 7.1     │
│ 5300108                         ┆ Brasília (DF)      ┆ 11.4  ┆ 6.0   ┆ 9.2   ┆ 12.1  ┆ 11.8    │
│ Fonte: IBGE - Censo Demográfic… ┆ null               ┆ null  ┆ null  ┆ null  ┆ null  ┆ null    │
└─────────────────────────────────┴────────────────────┴───────┴───────┴───────┴───────┴─────────┘
Number of missing values: shape: (1, 7)
┌────────┬──────┬───────┬───────┬───────┬───────┬─────────┐
│ codigo ┆ nome ┆ total ┆ 11_14 ┆ 15_17 ┆ 18_24 ┆ 25_mais │
│ ---    ┆ ---  ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---     │
│ u32    ┆ u32  ┆ u32   ┆ u32   ┆ u32   ┆ u32   ┆ u32     │
╞════════╪══════╪═══════╪═══════╪═══════╪═══════╪═════════╡
│ 0      ┆ 1    ┆ 1     ┆ 1     ┆ 1     ┆ 1     ┆ 1       │
└────────┴──────┴───────┴───────┴───────┴───────┴─────────┘
Number of duplicates: 0
Number of unique values: 5571
File: tabela6803 - taxa_rede_esgoto.xlsx
Number of rows: 5570
Number of columns: 4
Columns: ['codigo', 'nome', 'nao', 'sim']
First 3 rows:
shape: (3, 4)
┌─────────┬────────────────────────────┬───────┬───────┐
│ codigo  ┆ nome                       ┆ nao   ┆ sim   │
│ ---     ┆ ---                        ┆ ---   ┆ ---   │
│ str     ┆ str                        ┆ f64   ┆ f64   │
╞═════════╪════════════════════════════╪═══════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 66.26 ┆ 33.73 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 34.64 ┆ 65.37 │
│ 1100031 ┆ Cabixi (RO)                ┆ 50.64 ┆ 49.37 │
└─────────┴────────────────────────────┴───────┴───────┘
Last 3 rows:
shape: (3, 4)
┌─────────┬────────────────────┬───────┬───────┐
│ codigo  ┆ nome               ┆ nao   ┆ sim   │
│ ---     ┆ ---                ┆ ---   ┆ ---   │
│ str     ┆ str                ┆ f64   ┆ f64   │
╞═════════╪════════════════════╪═══════╪═══════╡
│ 5222203 ┆ Vila Boa (GO)      ┆ 25.33 ┆ 74.67 │
│ 5222302 ┆ Vila Propício (GO) ┆ 39.31 ┆ 60.68 │
│ 5300108 ┆ Brasília (DF)      ┆ 5.91  ┆ 94.1  │
└─────────┴────────────────────┴───────┴───────┘
Number of missing values: shape: (1, 4)
┌────────┬──────┬─────┬─────┐
│ codigo ┆ nome ┆ nao ┆ sim │
│ ---    ┆ ---  ┆ --- ┆ --- │
│ u32    ┆ u32  ┆ u32 ┆ u32 │
╞════════╪══════╪═════╪═════╡
│ 0      ┆ 0    ┆ 4   ┆ 0   │
└────────┴──────┴─────┴─────┘
Number of duplicates: 0
Number of unique values: 5570
File: tabela6892 - taxa_coleta_lixo.xlsx
Number of rows: 5571
Number of columns: 3
Columns: ['codigo', 'nome', 'pct_coletado']
First 3 rows:
shape: (3, 3)
┌─────────┬────────────────────────────┬──────────────┐
│ codigo  ┆ nome                       ┆ pct_coletado │
│ ---     ┆ ---                        ┆ ---          │
│ str     ┆ str                        ┆ f64          │
╞═════════╪════════════════════════════╪══════════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 61.48        │
│ 1100023 ┆ Ariquemes (RO)             ┆ 90.42        │
│ 1100031 ┆ Cabixi (RO)                ┆ 61.06        │
└─────────┴────────────────────────────┴──────────────┘
Last 3 rows:
shape: (3, 3)
┌─────────────────────────────────┬────────────────────┬──────────────┐
│ codigo                          ┆ nome               ┆ pct_coletado │
│ ---                             ┆ ---                ┆ ---          │
│ str                             ┆ str                ┆ f64          │
╞═════════════════════════════════╪════════════════════╪══════════════╡
│ 5222302                         ┆ Vila Propício (GO) ┆ 62.98        │
│ 5300108                         ┆ Brasília (DF)      ┆ 98.91        │
│ Fonte: IBGE - Censo Demográfic… ┆ null               ┆ null         │
└─────────────────────────────────┴────────────────────┴──────────────┘
Number of missing values: shape: (1, 3)
┌────────┬──────┬──────────────┐
│ codigo ┆ nome ┆ pct_coletado │
│ ---    ┆ ---  ┆ ---          │
│ u32    ┆ u32  ┆ u32          │
╞════════╪══════╪══════════════╡
│ 0      ┆ 1    ┆ 1            │
└────────┴──────┴──────────────┘
Number of duplicates: 0
Number of unique values: 5571
File: tabela9514 - taxa_distribuicao_etaria.xlsx
Number of rows: 5570
Number of columns: 3
Columns: ['codigo', 'nome', 'pct_60_mais']
First 3 rows:
shape: (3, 3)
┌─────────┬────────────────────────────┬─────────────┐
│ codigo  ┆ nome                       ┆ pct_60_mais │
│ ---     ┆ ---                        ┆ ---         │
│ str     ┆ str                        ┆ f64         │
╞═════════╪════════════════════════════╪═════════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 14.53       │
│ 1100023 ┆ Ariquemes (RO)             ┆ 11.54       │
│ 1100031 ┆ Cabixi (RO)                ┆ 19.23       │
└─────────┴────────────────────────────┴─────────────┘
Last 3 rows:
shape: (3, 3)
┌─────────┬────────────────────┬─────────────┐
│ codigo  ┆ nome               ┆ pct_60_mais │
│ ---     ┆ ---                ┆ ---         │
│ str     ┆ str                ┆ f64         │
╞═════════╪════════════════════╪═════════════╡
│ 5222203 ┆ Vila Boa (GO)      ┆ 11.98       │
│ 5222302 ┆ Vila Propício (GO) ┆ 15.94       │
│ 5300108 ┆ Brasília (DF)      ┆ 12.96       │
└─────────┴────────────────────┴─────────────┘
Number of missing values: shape: (1, 3)
┌────────┬──────┬─────────────┐
│ codigo ┆ nome ┆ pct_60_mais │
│ ---    ┆ ---  ┆ ---         │
│ u32    ┆ u32  ┆ u32         │
╞════════╪══════╪═════════════╡
│ 0      ┆ 0    ┆ 0           │
└────────┴──────┴─────────────┘
Number of duplicates: 0
Number of unique values: 5570
File: tabela9543 - taxa_de_alfabetizacao.xlsx
Number of rows: 5570
Number of columns: 3
Columns: ['codigo', 'nome', 'total']
First 3 rows:
shape: (3, 3)
┌─────────┬────────────────────────────┬───────┐
│ codigo  ┆ nome                       ┆ total │
│ ---     ┆ ---                        ┆ ---   │
│ str     ┆ str                        ┆ f64   │
╞═════════╪════════════════════════════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 91.59 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 94.08 │
│ 1100031 ┆ Cabixi (RO)                ┆ 89.82 │
└─────────┴────────────────────────────┴───────┘
Last 3 rows:
shape: (3, 3)
┌─────────┬────────────────────┬───────┐
│ codigo  ┆ nome               ┆ total │
│ ---     ┆ ---                ┆ ---   │
│ str     ┆ str                ┆ f64   │
╞═════════╪════════════════════╪═══════╡
│ 5222203 ┆ Vila Boa (GO)      ┆ 87.17 │
│ 5222302 ┆ Vila Propício (GO) ┆ 85.68 │
│ 5300108 ┆ Brasília (DF)      ┆ 97.23 │
└─────────┴────────────────────┴───────┘
Number of missing values: shape: (1, 3)
┌────────┬──────┬───────┐
│ codigo ┆ nome ┆ total │
│ ---    ┆ ---  ┆ ---   │
│ u32    ┆ u32  ┆ u32   │
╞════════╪══════╪═══════╡
│ 0      ┆ 0    ┆ 0     │
└────────┴──────┴───────┘
Number of duplicates: 0
Number of unique values: 5570
File: tabela9884 - pop_res_favela.xlsx
Number of rows: 656
Number of columns: 3
Columns: ['codigo', 'nome', 'total']
First 3 rows:
shape: (3, 3)
┌─────────┬────────────────────┬───────┐
│ codigo  ┆ nome               ┆ total │
│ ---     ┆ ---                ┆ ---   │
│ str     ┆ str                ┆ i64   │
╞═════════╪════════════════════╪═══════╡
│ 1100049 ┆ Cacoal (RO)        ┆ 543   │
│ 1100106 ┆ Guajará-Mirim (RO) ┆ 2943  │
│ 1100205 ┆ Porto Velho (RO)   ┆ 79809 │
└─────────┴────────────────────┴───────┘
Last 3 rows:
shape: (3, 3)
┌─────────┬──────────────────────────┬────────┐
│ codigo  ┆ nome                     ┆ total  │
│ ---     ┆ ---                      ┆ ---    │
│ str     ┆ str                      ┆ i64    │
╞═════════╪══════════════════════════╪════════╡
│ 5221858 ┆ Valparaíso de Goiás (GO) ┆ 3832   │
│ 5222302 ┆ Vila Propício (GO)       ┆ 174    │
│ 5300108 ┆ Brasília (DF)            ┆ 198779 │
└─────────┴──────────────────────────┴────────┘
Number of missing values: shape: (1, 3)
┌────────┬──────┬───────┐
│ codigo ┆ nome ┆ total │
│ ---    ┆ ---  ┆ ---   │
│ u32    ┆ u32  ┆ u32   │
╞════════╪══════╪═══════╡
│ 0      ┆ 0    ┆ 0     │
└────────┴──────┴───────┘
Number of duplicates: 0
Number of unique values: 656
File: tabela9923 - taxa_situacao_domicilio.xlsx
Number of rows: 5570
Number of columns: 4
Columns: ['codigo', 'nome', 'urbana', 'rural']
First 3 rows:
shape: (3, 4)
┌─────────┬────────────────────────────┬────────┬───────┐
│ codigo  ┆ nome                       ┆ urbana ┆ rural │
│ ---     ┆ ---                        ┆ ---    ┆ ---   │
│ str     ┆ str                        ┆ f64    ┆ f64   │
╞═════════╪════════════════════════════╪════════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 60.35  ┆ 39.65 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 86.7   ┆ 13.3  │
│ 1100031 ┆ Cabixi (RO)                ┆ 53.19  ┆ 46.81 │
└─────────┴────────────────────────────┴────────┴───────┘
Last 3 rows:
shape: (3, 4)
┌─────────┬────────────────────┬────────┬───────┐
│ codigo  ┆ nome               ┆ urbana ┆ rural │
│ ---     ┆ ---                ┆ ---    ┆ ---   │
│ str     ┆ str                ┆ f64    ┆ f64   │
╞═════════╪════════════════════╪════════╪═══════╡
│ 5222203 ┆ Vila Boa (GO)      ┆ 78.84  ┆ 21.16 │
│ 5222302 ┆ Vila Propício (GO) ┆ 60.74  ┆ 39.26 │
│ 5300108 ┆ Brasília (DF)      ┆ 96.48  ┆ 3.52  │
└─────────┴────────────────────┴────────┴───────┘
Number of missing values: shape: (1, 4)
┌────────┬──────┬────────┬───────┐
│ codigo ┆ nome ┆ urbana ┆ rural │
│ ---    ┆ ---  ┆ ---    ┆ ---   │
│ u32    ┆ u32  ┆ u32    ┆ u32   │
╞════════╪══════╪════════╪═══════╡
│ 0      ┆ 0    ┆ 0      ┆ 32    │
└────────┴──────┴────────┴───────┘
Number of duplicates: 0
Number of unique values: 5570

In [3]:
pl.read_parquet('data/mortalidade_final/mortalidade_2022.parquet')

shape: (1_544_266, 89)
┌────────┬──────────┬──────────┬───────────┬───┬──────────┬──────────┬──────────────┬──────────────┐
│ ORIGEM ┆ TIPOBITO ┆ DTOBITO  ┆ HORAOBITO ┆ … ┆ ALTCAUSA ┆ CONTADOR ┆ NO_MUNICIPIO ┆ CO_SIGLA_EST │
│ ---    ┆ ---      ┆ ---      ┆ ---       ┆   ┆ ---      ┆ ---      ┆ ---          ┆ ADO          │
│ str    ┆ str      ┆ str      ┆ str       ┆   ┆ str      ┆ str      ┆ str          ┆ ---          │
│        ┆          ┆          ┆           ┆   ┆          ┆          ┆              ┆ str          │
╞════════╪══════════╪══════════╪═══════════╪═══╪══════════╪══════════╪══════════════╪══════════════╡
│ 1      ┆ 2        ┆ 21042022 ┆ 1230      ┆ … ┆          ┆ 1        ┆ SANTOS       ┆ SP           │
│ 1      ┆ 2        ┆ 22042022 ┆ 1203      ┆ … ┆          ┆ 2        ┆ SANTOS       ┆ SP           │
│ 1      ┆ 2        ┆ 22042022 ┆ 1525      ┆ … ┆          ┆ 3        ┆ SANTOS       ┆ SP           │
│ 1      ┆ 2        ┆ 23042022 ┆ 0937      ┆ … ┆          ┆ 4        ┆ SANTOS       ┆ SP           │
│ 1      ┆ 2        ┆ 20042022 ┆ 1351      ┆ … ┆          ┆ 5        ┆ SANTOS       ┆ SP           │
│ …      ┆ …        ┆ …        ┆ …         ┆ … ┆ …        ┆ …        ┆ …            ┆ …            │
│ 1      ┆ 2        ┆ 01122022 ┆ 0100      ┆ … ┆          ┆ 1544262  ┆ EIRUNEPE     ┆ AM           │
│ 1      ┆ 2        ┆ 02092022 ┆ 1520      ┆ … ┆          ┆ 1544263  ┆ JAPURA       ┆ AM           │
│ 1      ┆ 2        ┆ 20072022 ┆ 0630      ┆ … ┆          ┆ 1544264  ┆ TARAUACA     ┆ AC           │
│ 1      ┆ 2        ┆ 08092022 ┆ 2000      ┆ … ┆          ┆ 1544265  ┆ TARAUACA     ┆ AC           │
│ 1      ┆ 2        ┆ 01072022 ┆           ┆ … ┆          ┆ 1544266  ┆ CUMARU DO    ┆ PA           │
│        ┆          ┆          ┆           ┆   ┆          ┆          ┆ NORTE        ┆              │
└────────┴──────────┴──────────┴───────────┴───┴──────────┴──────────┴──────────────┴──────────────┘

In [2]:
# Estrutura de diretórios para armazenar os dados brutos e os convertidos
nome_pasta = 'cnes_2024'
base_dir = Path(nome_pasta)
raw_dir = base_dir / "raw"
parquet_dir = base_dir / "parquet"

# Criar os diretórios, se ainda não existirem
raw_dir.mkdir(parents=True, exist_ok=True)
parquet_dir.mkdir(parents=True, exist_ok=True)

base_dir, raw_dir, parquet_dir

(WindowsPath('cnes_2024'),
 WindowsPath('cnes_2024/raw'),
 WindowsPath('cnes_2024/parquet'))

In [ ]:
# 📁 Pastas locais
RAW_DIR = f'{nome_pasta}/raw'
PARQUET_DIR = f'{nome_pasta}/parquet'
os.makedirs(RAW_DIR, exist_ok=True)
os.makedirs(PARQUET_DIR, exist_ok=True)
ano = '2024'

# 📦 Tabelas de interesse (nomes de prefixo nos arquivos)
TABELAS_INTERESSE = [
    'rlEstabComplementar',
    'tbAtributo',
    'tbEstabelecimento',
    'tbMunicipio',
    'tbEstado',
    'tbTipoUnidade',
    'tbTipoEstabelecimento',
    'tbAtividade',
    'tbAtividadeProfissional',
]

# 📅 Meses a baixar
MESES = [f'{mes:02d}' for mes in range(1, 13)]

# 🔽 Baixa e extrai arquivos CSV específicos do ZIP

def baixar_e_extrair(mes, ano=ano):
    competencia = f'{ano}{mes}'
    arquivo_zip = f'BASE_DE_DADOS_CNES_{competencia}.zip'
    print(f'🔽 Baixando {arquivo_zip}...')

    ftp = FTP('ftp.datasus.gov.br')
    ftp.login()
    ftp.cwd('cnes')  # Diretório correto de acordo com sua observação

    caminho_local = os.path.join(RAW_DIR, arquivo_zip)
    with open(caminho_local, 'wb') as f:
        ftp.retrbinary(f'RETR {arquivo_zip}', f.write)

    ftp.quit()

    # Extrai apenas os CSVs de interesse
    print(f'📦 Extraindo arquivos de interesse de {arquivo_zip}...')
    with zipfile.ZipFile(caminho_local, 'r') as zip_ref:
        for nome_arquivo in zip_ref.namelist():
            for base in TABELAS_INTERESSE:
                if nome_arquivo.lower().startswith(base.lower()) and nome_arquivo.lower().endswith('.csv'):
                    zip_ref.extract(nome_arquivo, RAW_DIR)

# 🧪 Converte arquivos CSV extraídos para Parquet usando Polars

def converter_csv_para_parquet():
    for nome_arquivo in os.listdir(RAW_DIR):
        if nome_arquivo.lower().endswith('.csv'):
            caminho_csv = os.path.join(RAW_DIR, nome_arquivo)
            nome_base = nome_arquivo.split('.')[0]
            nome_base_sem_data = ''.join(filter(str.isalpha, nome_base))

            if nome_base_sem_data.lower() not in [t.lower() for t in TABELAS_INTERESSE]:
                continue

            print(f'📄 Convertendo {nome_arquivo} → {nome_base}.parquet')

            df = pl.read_csv(
                caminho_csv, 
                encoding='latin1', 
                separator=';', 
                low_memory=True,
                schema_overrides={
                    'CO_UNIDADE': pl.Utf8
                }
            )
            df.write_parquet(os.path.join(PARQUET_DIR, f'{nome_base}.parquet'))

# 🚀 Execução
for mes in MESES:
    baixar_e_extrair(mes)

converter_csv_para_parquet()
print("✅ Processo finalizado com sucesso!")

🔽 Baixando BASE_DE_DADOS_CNES_202401.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202401.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202402.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202402.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202403.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202403.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202404.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202404.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202405.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202405.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202406.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202406.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202407.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202407.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202408.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202408.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202409.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202409.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202410.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202410.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202411.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202411.zip...
🔽 Baixando BASE_DE_DADOS_CNES_202412.zip...
📦 Extraindo arquivos de interesse de BASE_DE_DADOS_CNES_202412.zip...
📄 Convertendo rlEstabComplementar202401.csv → rlEstabComplementar202401.parquet

ComputeError: could not parse `"CE00000000000000006580724000138"` as dtype `i64` at column 'CO_UNIDADE' (column number 1)

The current offset in the file is 17318 bytes.

You might want to try:
- increasing `infer_schema_length` (e.g. `infer_schema_length=10000`),
- specifying correct dtype with the `schema_overrides` argument
- setting `ignore_errors` to `True`,
- adding `"CE00000000000000006580724000138"` to the `null_values` list.

Original error: ```remaining bytes non-empty```

In [4]:
def converter_csv_para_parquet():
    for nome_arquivo in os.listdir(RAW_DIR):
        if nome_arquivo.lower().endswith('.csv'):
            caminho_csv = os.path.join(RAW_DIR, nome_arquivo)
            nome_base = nome_arquivo.split('.')[0]
            nome_base_sem_data = ''.join(filter(str.isalpha, nome_base))

            if nome_base_sem_data.lower() not in [t.lower() for t in TABELAS_INTERESSE]:
                continue

            print(f'📄 Convertendo {nome_arquivo} → {nome_base}.parquet')

            df = pl.read_csv(
                caminho_csv, 
                encoding='latin1', 
                separator=';', 
                low_memory=True,
                schema_overrides={
                    'CO_UNIDADE': pl.Utf8
                }
            )
            df.write_parquet(os.path.join(PARQUET_DIR, f'{nome_base}.parquet'))

converter_csv_para_parquet()
print("✅ Processo finalizado com sucesso!")

📄 Convertendo rlEstabComplementar202401.csv → rlEstabComplementar202401.parquet
📄 Convertendo rlEstabComplementar202402.csv → rlEstabComplementar202402.parquet
📄 Convertendo rlEstabComplementar202403.csv → rlEstabComplementar202403.parquet
📄 Convertendo rlEstabComplementar202404.csv → rlEstabComplementar202404.parquet
📄 Convertendo rlEstabComplementar202405.csv → rlEstabComplementar202405.parquet
📄 Convertendo rlEstabComplementar202406.csv → rlEstabComplementar202406.parquet
📄 Convertendo rlEstabComplementar202407.csv → rlEstabComplementar202407.parquet
📄 Convertendo rlEstabComplementar202408.csv → rlEstabComplementar202408.parquet
📄 Convertendo rlEstabComplementar202409.csv → rlEstabComplementar202409.parquet
📄 Convertendo rlEstabComplementar202410.csv → rlEstabComplementar202410.parquet
📄 Convertendo rlEstabComplementar202411.csv → rlEstabComplementar202411.parquet
📄 Convertendo rlEstabComplementar202412.csv → rlEstabComplementar202412.parquet
📄 Convertendo tbAtividade202401.csv → tbAtividade202401.parquet
📄 Convertendo tbAtividade202402.csv → tbAtividade202402.parquet
📄 Convertendo tbAtividade202403.csv → tbAtividade202403.parquet
📄 Convertendo tbAtividade202404.csv → tbAtividade202404.parquet
📄 Convertendo tbAtividade202405.csv → tbAtividade202405.parquet
📄 Convertendo tbAtividade202406.csv → tbAtividade202406.parquet
📄 Convertendo tbAtividade202407.csv → tbAtividade202407.parquet
📄 Convertendo tbAtividade202408.csv → tbAtividade202408.parquet
📄 Convertendo tbAtividade202409.csv → tbAtividade202409.parquet
📄 Convertendo tbAtividade202410.csv → tbAtividade202410.parquet
📄 Convertendo tbAtividade202411.csv → tbAtividade202411.parquet
📄 Convertendo tbAtividade202412.csv → tbAtividade202412.parquet
📄 Convertendo tbAtividadeProfissional202401.csv → tbAtividadeProfissional202401.parquet
📄 Convertendo tbAtividadeProfissional202402.csv → tbAtividadeProfissional202402.parquet
📄 Convertendo tbAtividadeProfissional202403.csv → tbAtividadeProfissional202403.parquet
📄 Convertendo tbAtividadeProfissional202404.csv → tbAtividadeProfissional202404.parquet
📄 Convertendo tbAtividadeProfissional202405.csv → tbAtividadeProfissional202405.parquet
📄 Convertendo tbAtividadeProfissional202406.csv → tbAtividadeProfissional202406.parquet
📄 Convertendo tbAtividadeProfissional202407.csv → tbAtividadeProfissional202407.parquet
📄 Convertendo tbAtividadeProfissional202408.csv → tbAtividadeProfissional202408.parquet
📄 Convertendo tbAtividadeProfissional202409.csv → tbAtividadeProfissional202409.parquet
📄 Convertendo tbAtividadeProfissional202410.csv → tbAtividadeProfissional202410.parquet
📄 Convertendo tbAtividadeProfissional202411.csv → tbAtividadeProfissional202411.parquet
📄 Convertendo tbAtividadeProfissional202412.csv → tbAtividadeProfissional202412.parquet
📄 Convertendo tbAtributo202401.csv → tbAtributo202401.parquet
📄 Convertendo tbAtributo202402.csv → tbAtributo202402.parquet
📄 Convertendo tbAtributo202403.csv → tbAtributo202403.parquet
📄 Convertendo tbAtributo202404.csv → tbAtributo202404.parquet
📄 Convertendo tbAtributo202405.csv → tbAtributo202405.parquet
📄 Convertendo tbAtributo202406.csv → tbAtributo202406.parquet
📄 Convertendo tbAtributo202407.csv → tbAtributo202407.parquet
📄 Convertendo tbAtributo202408.csv → tbAtributo202408.parquet
📄 Convertendo tbAtributo202409.csv → tbAtributo202409.parquet
📄 Convertendo tbAtributo202410.csv → tbAtributo202410.parquet
📄 Convertendo tbAtributo202411.csv → tbAtributo202411.parquet
📄 Convertendo tbAtributo202412.csv → tbAtributo202412.parquet
📄 Convertendo tbEstabelecimento202401.csv → tbEstabelecimento202401.parquet
📄 Convertendo tbEstabelecimento202402.csv → tbEstabelecimento202402.parquet
📄 Convertendo tbEstabelecimento202403.csv → tbEstabelecimento202403.parquet
📄 Convertendo tbEstabelecimento202404.csv → tbEstabelecimento202404.parquet
📄 Convertendo tbEstabelecimento202405.csv → tbEstabelecimento202405.parquet
📄 Convertendo tbEstabelecimento202406.csv → tbEstabelecimento202406.parquet
📄 Convertendo tbEstabelecimento202407.csv → tbEstabelecimento202407.parquet
📄 Convertendo tbEstabelecimento202408.csv → tbEstabelecimento202408.parquet
📄 Convertendo tbEstabelecimento202409.csv → tbEstabelecimento202409.parquet
📄 Convertendo tbEstabelecimento202410.csv → tbEstabelecimento202410.parquet
📄 Convertendo tbEstabelecimento202411.csv → tbEstabelecimento202411.parquet
📄 Convertendo tbEstabelecimento202412.csv → tbEstabelecimento202412.parquet
📄 Convertendo tbEstado202401.csv → tbEstado202401.parquet
📄 Convertendo tbEstado202402.csv → tbEstado202402.parquet
📄 Convertendo tbEstado202403.csv → tbEstado202403.parquet
📄 Convertendo tbEstado202404.csv → tbEstado202404.parquet
📄 Convertendo tbEstado202405.csv → tbEstado202405.parquet
📄 Convertendo tbEstado202406.csv → tbEstado202406.parquet
📄 Convertendo tbEstado202407.csv → tbEstado202407.parquet
📄 Convertendo tbEstado202408.csv → tbEstado202408.parquet
📄 Convertendo tbEstado202409.csv → tbEstado202409.parquet
📄 Convertendo tbEstado202410.csv → tbEstado202410.parquet
📄 Convertendo tbEstado202411.csv → tbEstado202411.parquet
📄 Convertendo tbEstado202412.csv → tbEstado202412.parquet
📄 Convertendo tbMunicipio202401.csv → tbMunicipio202401.parquet
📄 Convertendo tbMunicipio202402.csv → tbMunicipio202402.parquet
📄 Convertendo tbMunicipio202403.csv → tbMunicipio202403.parquet
📄 Convertendo tbMunicipio202404.csv → tbMunicipio202404.parquet
📄 Convertendo tbMunicipio202405.csv → tbMunicipio202405.parquet
📄 Convertendo tbMunicipio202406.csv → tbMunicipio202406.parquet
📄 Convertendo tbMunicipio202407.csv → tbMunicipio202407.parquet
📄 Convertendo tbMunicipio202408.csv → tbMunicipio202408.parquet
📄 Convertendo tbMunicipio202409.csv → tbMunicipio202409.parquet
📄 Convertendo tbMunicipio202410.csv → tbMunicipio202410.parquet
📄 Convertendo tbMunicipio202411.csv → tbMunicipio202411.parquet
📄 Convertendo tbMunicipio202412.csv → tbMunicipio202412.parquet
📄 Convertendo tbTipoEstabelecimento202401.csv → tbTipoEstabelecimento202401.parquet
📄 Convertendo tbTipoEstabelecimento202402.csv → tbTipoEstabelecimento202402.parquet
📄 Convertendo tbTipoEstabelecimento202403.csv → tbTipoEstabelecimento202403.parquet
📄 Convertendo tbTipoEstabelecimento202404.csv → tbTipoEstabelecimento202404.parquet
📄 Convertendo tbTipoEstabelecimento202405.csv → tbTipoEstabelecimento202405.parquet
📄 Convertendo tbTipoEstabelecimento202406.csv → tbTipoEstabelecimento202406.parquet
📄 Convertendo tbTipoEstabelecimento202407.csv → tbTipoEstabelecimento202407.parquet
📄 Convertendo tbTipoEstabelecimento202408.csv → tbTipoEstabelecimento202408.parquet
📄 Convertendo tbTipoEstabelecimento202409.csv → tbTipoEstabelecimento202409.parquet
📄 Convertendo tbTipoEstabelecimento202410.csv → tbTipoEstabelecimento202410.parquet
📄 Convertendo tbTipoEstabelecimento202411.csv → tbTipoEstabelecimento202411.parquet
📄 Convertendo tbTipoEstabelecimento202412.csv → tbTipoEstabelecimento202412.parquet
📄 Convertendo tbTipoUnidade202401.csv → tbTipoUnidade202401.parquet
📄 Convertendo tbTipoUnidade202402.csv → tbTipoUnidade202402.parquet
📄 Convertendo tbTipoUnidade202403.csv → tbTipoUnidade202403.parquet
📄 Convertendo tbTipoUnidade202404.csv → tbTipoUnidade202404.parquet
📄 Convertendo tbTipoUnidade202405.csv → tbTipoUnidade202405.parquet
📄 Convertendo tbTipoUnidade202406.csv → tbTipoUnidade202406.parquet
📄 Convertendo tbTipoUnidade202407.csv → tbTipoUnidade202407.parquet
📄 Convertendo tbTipoUnidade202408.csv → tbTipoUnidade202408.parquet
📄 Convertendo tbTipoUnidade202409.csv → tbTipoUnidade202409.parquet
📄 Convertendo tbTipoUnidade202410.csv → tbTipoUnidade202410.parquet
📄 Convertendo tbTipoUnidade202411.csv → tbTipoUnidade202411.parquet
📄 Convertendo tbTipoUnidade202412.csv → tbTipoUnidade202412.parquet
✅ Processo finalizado com sucesso!

In [5]:
# Análise de registro das colunas de cada tabela

arquivos = [
    'tbEstabelecimento202412',
    'rlEstabComplementar202412',
    'tbAtributo202412',
    'tbMunicipio202412',
    'tbEstado202412',
    'tbTipoUnidade202412',
    'tbTipoEstabelecimento202412',
    'tbAtividade202412',
    'tbAtividadeProfissional202412'
]

for arquivo in arquivos:
    df = pl.read_parquet(os.path.join(PARQUET_DIR, f'{arquivo}.parquet'))
    print(f'🔍 Exibindo a contagem de registros de todas as colunas da tabela {arquivo}.parquet -> Shape: ', df.shape, '\n')
    for col in df.columns:
        print(f'{df[col].value_counts()}')
    print('\n' + '-'*100 + '\n')

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbEstabelecimento202412.parquet -> Shape:  (557329, 56)

shape: (557_329, 2)
┌───────────────┬───────┐
│ CO_UNIDADE    ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ 2925206609708 ┆ 1     │
│ 4107204272293 ┆ 1     │
│ 3304550739359 ┆ 1     │
│ 3515503735613 ┆ 1     │
│ 4310207115334 ┆ 1     │
│ …             ┆ …     │
│ 3514409772278 ┆ 1     │
│ 3549804293878 ┆ 1     │
│ 5002707608543 ┆ 1     │
│ 2211002360845 ┆ 1     │
│ 2901009055932 ┆ 1     │
└───────────────┴───────┘
shape: (557_329, 2)
┌─────────┬───────┐
│ CO_CNES ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 110116  ┆ 1     │
│ 6493025 ┆ 1     │
│ 4073371 ┆ 1     │
│ 510505  ┆ 1     │
│ 2974118 ┆ 1     │
│ …       ┆ …     │
│ 4609522 ┆ 1     │
│ 7019807 ┆ 1     │
│ 7620438 ┆ 1     │
│ 9971041 ┆ 1     │
│ 656666  ┆ 1     │
└─────────┴───────┘
shape: (7_270, 2)
┌─────────────────────┬───────┐
│ NU_CNPJ_MANTENEDORA ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ 55755862000116      ┆ 1     │
│ 11361870000102      ┆ 16    │
│ 00394544003443      ┆ 17    │
│ 27165646000185      ┆ 17    │
│ 11208239000178      ┆ 1     │
│ …                   ┆ …     │
│ 07606478000109      ┆ 8     │
│ 10572048000128      ┆ 126   │
│ 03501517000152      ┆ 19    │
│ 12261228000114      ┆ 24    │
│ 12097798000110      ┆ 4     │
└─────────────────────┴───────┘
shape: (2, 2)
┌─────────┬────────┐
│ TP_PFPJ ┆ count  │
│ ---     ┆ ---    │
│ i64     ┆ u32    │
╞═════════╪════════╡
│ 1       ┆ 162130 │
│ 3       ┆ 395199 │
└─────────┴────────┘
shape: (2, 2)
┌───────────┬────────┐
│ NIVEL_DEP ┆ count  │
│ ---       ┆ ---    │
│ i64       ┆ u32    │
╞═══════════╪════════╡
│ 3         ┆ 114597 │
│ 1         ┆ 442732 │
└───────────┴────────┘
shape: (419_865, 2)
┌─────────────────────────────────┬───────┐
│ NO_RAZAO_SOCIAL                 ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ YSABEL CRISTINA DUTRA SERAFIM … ┆ 1     │
│ SORRICAMP CLINICA ODONTOLOGICA… ┆ 1     │
│ NORTON BIANCHINI DE OLIVEIRA    ┆ 1     │
│ CLAUDIO PAPINI DE MORAES        ┆ 1     │
│ VIDA SERVICOS DE TERAPIA INTEN… ┆ 1     │
│ …                               ┆ …     │
│ SANTANA PSICOLOGIA LTDA ME      ┆ 1     │
│ A J MOREIRA CESAR SERVICO E CO… ┆ 1     │
│ PANDOLFI BORRIERO SERVICOS SAU… ┆ 1     │
│ SERVICO DE OTORRINOLARINGOLOGI… ┆ 1     │
│ AMANDA MAYRINK MOURA SERVICOS … ┆ 1     │
└─────────────────────────────────┴───────┘
shape: (481_392, 2)
┌─────────────────────────────────┬───────┐
│ NO_FANTASIA                     ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ FERNANDA APARECIDA BRAITE CANO… ┆ 1     │
│ LABORATORIO BRASIL ANALISES CL… ┆ 1     │
│ UNIDADE BASICA DE SAUDE JORGE … ┆ 1     │
│ CONSULTORIO MEDICO DE GINECOLO… ┆ 1     │
│ NUDERMA                         ┆ 1     │
│ …                               ┆ …     │
│ SUELENA ROSANA RICO DE ARAUJO   ┆ 1     │
│ G R SERVICOS MEDICOS            ┆ 1     │
│ JAIRO DE CARVALHO JUNIOR CONSU… ┆ 1     │
│ CLINICA ESPEC 9 DE JULHO ENDOS… ┆ 1     │
│ CANDICE FABRI FANTI             ┆ 1     │
└─────────────────────────────────┴───────┘
shape: (175_985, 2)
┌─────────────────────────────────┬───────┐
│ NO_LOGRADOURO                   ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ AREA ESPECIAL LOTES             ┆ 1     │
│ VEREADOR LUIS MARQUES DO NASCI… ┆ 1     │
│ AV DAVINO MATTOS                ┆ 12    │
│ RUA EMILIO CARLOS               ┆ 1     │
│ CAREIRO DA VARZEA               ┆ 1     │
│ …                               ┆ …     │
│ RUA APARECIDA                   ┆ 20    │
│ AV PADRE JOAO EID               ┆ 1     │
│ 337 CJ NOVA METROPOLE           ┆ 1     │
│ AV TAIDE TEIVE                  ┆ 2     │
│ RUA CORONEL VAIANO              ┆ 8     │
└─────────────────────────────────┴───────┘
shape: (8_695, 2)
┌─────────────┬───────┐
│ NU_ENDERECO ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ 8941        ┆ 1     │
│ 286         ┆ 446   │
│ 1677        ┆ 44    │
│ 01340       ┆ 3     │
│ 14703       ┆ 1     │
│ …           ┆ …     │
│ 2468        ┆ 53    │
│ 2922        ┆ 6     │
│ 01097       ┆ 3     │
│ 3706        ┆ 4     │
│ 5770        ┆ 1     │
└─────────────┴───────┘
shape: (70_496, 2)
┌──────────────────────┬───────┐
│ NO_COMPLEMENTO       ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ SL704 7 ANDAR        ┆ 1     │
│ SALA 106 207 208     ┆ 1     │
│ B 2 SL 218           ┆ 1     │
│ UNIDADE 166 A        ┆ 1     │
│ SLA 133              ┆ 1     │
│ …                    ┆ …     │
│ PAVMTO2 QD02A LT 007 ┆ 1     │
│ CASA 76 COND PARQUE  ┆ 1     │
│ LOJA 02 SALA 01      ┆ 2     │
│ ANEXO A UMSC         ┆ 2     │
│ KM 0                 ┆ 7     │
└──────────────────────┴───────┘
shape: (35_710, 2)
┌──────────────────────┬───────┐
│ NO_BAIRRO            ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ VILA GUANUMBY        ┆ 2     │
│ PARQUE DAS ARVORES   ┆ 13    │
│ NOSSA SR APARECIDA   ┆ 1     │
│ DELPHINA AZIZ        ┆ 1     │
│ VILA FLORESTA NOVA   ┆ 1     │
│ …                    ┆ …     │
│ POVOADO JUA          ┆ 2     │
│ TIJUCAL              ┆ 11    │
│ DISTRITO DE CATOLE D ┆ 4     │
│ SALGADO FILHO        ┆ 444   │
│ VILA LUZIMANGUES     ┆ 1     │
└──────────────────────┴───────┘
shape: (102_918, 2)
┌──────────┬───────┐
│ CO_CEP   ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 80540010 ┆ 2     │
│ 38202166 ┆ 2     │
│ 13070070 ┆ 12    │
│ 74425250 ┆ 1     │
│ 84040140 ┆ 4     │
│ …        ┆ …     │
│ 4270020  ┆ 1     │
│ 74125090 ┆ 5     │
│ 64245000 ┆ 12    │
│ 57052790 ┆ 2     │
│ 21235090 ┆ 3     │
└──────────┴───────┘
shape: (1_017, 2)
┌─────────────────┬───────┐
│ CO_REGIAO_SAUDE ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ 20ª             ┆ 78    │
│ CR-L            ┆ 50    │
│ DRS6            ┆ 278   │
│ 50              ┆ 1     │
│ 3304            ┆ 9     │
│ …               ┆ …     │
│ 2112            ┆ 1     │
│ 67              ┆ 1     │
│ 05º             ┆ 4     │
│ 7RPS            ┆ 4     │
│ 115             ┆ 1     │
└─────────────────┴───────┘
shape: (1, 2)
┌─────────────────┬────────┐
│ CO_MICRO_REGIAO ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u32    │
╞═════════════════╪════════╡
│                 ┆ 557329 │
└─────────────────┴────────┘
shape: (139, 2)
┌───────────────────────┬───────┐
│ CO_DISTRITO_SANITARIO ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ 36                    ┆ 1     │
│ 0000                  ┆ 3     │
│ 6002                  ┆ 1     │
│ 11                    ┆ 97    │
│ 7771                  ┆ 1     │
│ …                     ┆ …     │
│ 16                    ┆ 3685  │
│ 010                   ┆ 16    │
│ 32                    ┆ 80    │
│ 9930                  ┆ 22    │
│ 0004                  ┆ 1126  │
└───────────────────────┴───────┘
shape: (161, 2)
┌────────────────────────────┬───────┐
│ CO_DISTRITO_ADMINISTRATIVO ┆ count │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ Q                          ┆ 1     │
│ 01                         ┆ 65    │
│ AMBU                       ┆ 1     │
│ 0059                       ┆ 1     │
│ 0015                       ┆ 2     │
│ …                          ┆ …     │
│ 004                        ┆ 1     │
│ POLO                       ┆ 1     │
│ 0049                       ┆ 1     │
│ 0011                       ┆ 3     │
│ 0046                       ┆ 4     │
└────────────────────────────┴───────┘
shape: (369_362, 2)
┌────────────────┬───────┐
│ NU_TELEFONE    ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ 19 38254580    ┆ 1     │
│ 51 31266000    ┆ 1     │
│ 28 3522-9301   ┆ 1     │
│ 32449071       ┆ 1     │
│ 22 2523-2223   ┆ 1     │
│ …              ┆ …     │
│ (65) 3623-6475 ┆ 1     │
│ 22 27726125    ┆ 1     │
│ (38)32319103   ┆ 4     │
│ (34)32363616   ┆ 1     │
│ 11 30796463    ┆ 1     │
└────────────────┴───────┘
shape: (1, 2)
┌────────┬────────┐
│ NU_FAX ┆ count  │
│ ---    ┆ ---    │
│ str    ┆ u32    │
╞════════╪════════╡
│        ┆ 557329 │
└────────┴────────┘
shape: (240_379, 2)
┌─────────────────────────────────┬───────┐
│ NO_EMAIL                        ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ marciocsouza@veloxmail.com.br   ┆ 1     │
│ raquel@oralvitae.com.br         ┆ 2     │
│ flaviaweb@hotmail.com           ┆ 1     │
│ oftalmoclinical@yahoo.com.br    ┆ 1     │
│ nataliabsilveira@yahoo.com.br   ┆ 1     │
│ …                               ┆ …     │
│ cida_analisys@hotmail.com       ┆ 1     │
│ ivantogni@unimedriopreto.com.b… ┆ 1     │
│ mentalcareceleste@gmail.com     ┆ 2     │
│ PSICOLOGALUFIGUEIREDO@GMAIL.CO… ┆ 1     │
│ kozmaodonto@gmail.com           ┆ 1     │
└─────────────────────────────────┴───────┘
shape: (154_458, 2)
┌─────────────┬───────┐
│ NU_CPF      ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ 26451352004 ┆ 1     │
│ 08131527808 ┆ 1     │
│ 27765203878 ┆ 1     │
│ 83898891615 ┆ 1     │
│ 06856326602 ┆ 1     │
│ …           ┆ …     │
│ 41041631804 ┆ 1     │
│ 69094039591 ┆ 1     │
│ 07536124880 ┆ 1     │
│ 07722706940 ┆ 2     │
│ 09067888702 ┆ 1     │
└─────────────┴───────┘
shape: (279_765, 2)
┌────────────────┬───────┐
│ NU_CNPJ        ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ 53715613000171 ┆ 1     │
│ 27172044000155 ┆ 1     │
│ 45453202000127 ┆ 1     │
│ 30671599000156 ┆ 1     │
│ 11721007000119 ┆ 1     │
│ …              ┆ …     │
│ 17530305000108 ┆ 1     │
│ 49889226000184 ┆ 1     │
│ 08485160000180 ┆ 1     │
│ 25358239000169 ┆ 1     │
│ 22103085000176 ┆ 1     │
└────────────────┴───────┘
shape: (5, 2)
┌──────────────┬────────┐
│ CO_ATIVIDADE ┆ count  │
│ ---          ┆ ---    │
│ i64          ┆ u32    │
╞══════════════╪════════╡
│ 2            ┆ 790    │
│ 5            ┆ 181    │
│ 3            ┆ 5580   │
│ 4            ┆ 549511 │
│ 1            ┆ 1267   │
└──────────────┴────────┘
shape: (4, 2)
┌──────────────┬────────┐
│ CO_CLIENTELA ┆ count  │
│ ---          ┆ ---    │
│ i64          ┆ u32    │
╞══════════════╪════════╡
│ 1            ┆ 214565 │
│ 3            ┆ 298524 │
│ 2            ┆ 36347  │
│ null         ┆ 7893   │
└──────────────┴────────┘
shape: (294_447, 2)
┌──────────────────────────┬───────┐
│ NU_ALVARA                ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ 354600391-851-000133-1-5 ┆ 1     │
│ 09/97/052803/2024        ┆ 1     │
│ 200702154500             ┆ 1     │
│ 4955699/2015             ┆ 1     │
│ 0402255                  ┆ 1     │
│ …                        ┆ …     │
│ 3110161630668/2013       ┆ 1     │
│ 6018.2022/0082502-3      ┆ 1     │
│ 0355/20                  ┆ 1     │
│ 354331900                ┆ 1     │
│ 09/97/069169/2024        ┆ 1     │
└──────────────────────────┴───────┘
shape: (11_804, 2)
┌──────────────────────┬───────┐
│ DT_EXPEDICAO         ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 17-jul-2024 00:00:00 ┆ 137   │
│ 02-jan-2011 00:00:00 ┆ 22    │
│ 18-mai-2004 00:00:00 ┆ 28    │
│ 15-abr-2018 00:00:00 ┆ 3     │
│ 23-nov-2009 00:00:00 ┆ 26    │
│ …                    ┆ …     │
│ 03-jul-2008 00:00:00 ┆ 50    │
│ 24-mar-2010 00:00:00 ┆ 41    │
│ 04-jan-2012 00:00:00 ┆ 31    │
│ 06-dez-2011 00:00:00 ┆ 42    │
│ 13-fev-2017 00:00:00 ┆ 46    │
└──────────────────────┴───────┘
shape: (4, 2)
┌────────────────────┬────────┐
│ TP_ORGAO_EXPEDIDOR ┆ count  │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│ 2                  ┆ 351885 │
│ 3                  ┆ 2      │
│                    ┆ 174093 │
│ 1                  ┆ 31349  │
└────────────────────┴────────┘
shape: (10_078, 2)
┌──────────────────────┬───────┐
│ DT_VAL_LIC_SANI      ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 15-jan-2099 00:00:00 ┆ 2     │
│ 23-ago-2050 00:00:00 ┆ 1     │
│ 17-jan-2015 00:00:00 ┆ 2     │
│ 19-jan-2023 00:00:00 ┆ 56    │
│ 30-out-2019 00:00:00 ┆ 47    │
│ …                    ┆ …     │
│ 02-ago-2009 00:00:00 ┆ 1     │
│ 29-jul-2010 00:00:00 ┆ 1     │
│ 12-jan-2014 00:00:00 ┆ 1     │
│ 04-jan-2015 00:00:00 ┆ 1     │
│ 05-jan-2015 00:00:00 ┆ 2     │
└──────────────────────┴───────┘
shape: (3, 2)
┌─────────────┬────────┐
│ TP_LIC_SANI ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│             ┆ 330924 │
│ 1           ┆ 206434 │
│ 2           ┆ 19971  │
└─────────────┴────────┘
shape: (39, 2)
┌────────────┬───────┐
│ TP_UNIDADE ┆ count │
│ ---        ┆ ---   │
│ i64        ┆ u32   │
╞════════════╪═══════╡
│ 79         ┆ 63    │
│ 21         ┆ 125   │
│ 7          ┆ 1434  │
│ 4          ┆ 14593 │
│ 77         ┆ 1964  │
│ …          ┆ …     │
│ 82         ┆ 139   │
│ 80         ┆ 974   │
│ 72         ┆ 1460  │
│ 61         ┆ 57    │
│ 81         ┆ 1551  │
└────────────┴───────┘
shape: (8, 2)
┌──────────────────────┬────────┐
│ CO_TURNO_ATENDIMENTO ┆ count  │
│ ---                  ┆ ---    │
│ i64                  ┆ u32    │
╞══════════════════════╪════════╡
│ 6                    ┆ 24716  │
│ 1                    ┆ 10797  │
│ 4                    ┆ 65858  │
│ 5                    ┆ 9768   │
│ null                 ┆ 1713   │
│ 2                    ┆ 16795  │
│ 3                    ┆ 426570 │
│ 7                    ┆ 1112   │
└──────────────────────┴────────┘
shape: (27, 2)
┌──────────────────┬───────┐
│ CO_ESTADO_GESTOR ┆ count │
│ ---              ┆ ---   │
│ i64              ┆ u32   │
╞══════════════════╪═══════╡
│ 51               ┆ 11540 │
│ 32               ┆ 11831 │
│ 29               ┆ 26638 │
│ 16               ┆ 1179  │
│ 50               ┆ 8327  │
│ …                ┆ …     │
│ 17               ┆ 3154  │
│ 31               ┆ 68685 │
│ 21               ┆ 8480  │
│ 52               ┆ 16242 │
│ 53               ┆ 11377 │
└──────────────────┴───────┘
shape: (5_584, 2)
┌─────────────────────┬───────┐
│ CO_MUNICIPIO_GESTOR ┆ count │
│ ---                 ┆ ---   │
│ i64                 ┆ u32   │
╞═════════════════════╪═══════╡
│ 316860              ┆ 641   │
│ 352760              ┆ 39    │
│ 314820              ┆ 16    │
│ 230160              ┆ 35    │
│ 230890              ┆ 24    │
│ …                   ┆ …     │
│ 241440              ┆ 39    │
│ 250920              ┆ 23    │
│ 260990              ┆ 93    │
│ 251200              ┆ 30    │
│ 411125              ┆ 32    │
└─────────────────────┴───────┘
shape: (6_366, 2)
┌─────────────────────────────────┬───────┐
│ TO_CHAR(DT_ATUALIZACAO,'DD/MM/… ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ 14/03/2007                      ┆ 6     │
│ 30/03/2006                      ┆ 20    │
│ 23/01/2007                      ┆ 4     │
│ 08/06/2007                      ┆ 6     │
│ 17/01/2022                      ┆ 49    │
│ …                               ┆ …     │
│ 17/12/2023                      ┆ 9     │
│ 10/03/2021                      ┆ 105   │
│ 03/07/2012                      ┆ 17    │
│ 23/10/2012                      ┆ 9     │
│ 20/05/2005                      ┆ 2     │
└─────────────────────────────────┴───────┘
shape: (8_335, 2)
┌────────────┬───────┐
│ CO_USUARIO ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ NANDA      ┆ 1     │
│ OZIEL      ┆ 152   │
│ BARRACAO   ┆ 23    │
│ ETHIANE    ┆ 18    │
│ CRESCER    ┆ 1     │
│ …          ┆ …     │
│ SMSA       ┆ 1     │
│ MXBASTOS   ┆ 1     │
│ JESSIE     ┆ 14    │
│ MÁRCIA     ┆ 1     │
│ MCOTAVARES ┆ 1     │
└────────────┴───────┘
shape: (436_594, 2)
┌──────────────────┬───────┐
│ CO_CPFDIRETORCLN ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│ 09778002703      ┆ 1     │
│ 05827908835      ┆ 1     │
│ 12979110752      ┆ 1     │
│ 46066969404      ┆ 1     │
│ 06504033803      ┆ 3     │
│ …                ┆ …     │
│ 16066979353      ┆ 1     │
│ 02111310590      ┆ 1     │
│ 21593656882      ┆ 1     │
│ 13490940644      ┆ 5     │
│ 00360337074      ┆ 2     │
└──────────────────┴───────┘
shape: (170_302, 2)
┌─────────────────┬───────┐
│ REG_DIRETORCLN  ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ 552669          ┆ 1     │
│ 107556          ┆ 1     │
│ 1218764         ┆ 1     │
│ CREFITO 67301-F ┆ 1     │
│ 109459F         ┆ 1     │
│ …               ┆ …     │
│ 34126           ┆ 2     │
│ 84241           ┆ 2     │
│ 93979           ┆ 1     │
│ 20931           ┆ 2     │
│ 347769          ┆ 1     │
└─────────────────┴───────┘
shape: (4, 2)
┌─────────────────────┬────────┐
│ ST_ADESAO_FILANTROP ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ u32    │
╞═════════════════════╪════════╡
│ 1                   ┆ 627    │
│ 2                   ┆ 1430   │
│                     ┆ 546    │
│                     ┆ 554726 │
└─────────────────────┴────────┘
shape: (15, 2)
┌─────────────────┬────────┐
│ CO_MOTIVO_DESAB ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u32    │
╞═════════════════╪════════╡
│ 10              ┆ 20337  │
│ 04              ┆ 30824  │
│                 ┆ 445306 │
│ 06              ┆ 13378  │
│ 05              ┆ 39     │
│ …               ┆ …      │
│ 01              ┆ 816    │
│ 13              ┆ 315    │
│ 11              ┆ 2815   │
│ 02              ┆ 59     │
│ 12              ┆ 24     │
└─────────────────┴────────┘
shape: (8_062, 2)
┌─────────────────────────────────┬────────┐
│ NO_URL                          ┆ count  │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│                                 ┆ 546534 │
│ MOMBELLI.IMRO@GMAIL.COM         ┆ 1      │
│ contabil.juk@gmail.com          ┆ 1      │
│ fisioclinicaphysicocenter.com.… ┆ 1      │
│ contato@redefemininasc.com.br   ┆ 1      │
│ …                               ┆ …      │
│ tesla.camaqua@gmail.com         ┆ 1      │
│ FILIAL011@FARMACIASSANTANA.COM… ┆ 1      │
│ contato@clinicaello.com.br      ┆ 1      │
│ www.sparkleexclusive.com        ┆ 1      │
│ www.bogonioftalmologia.com.br   ┆ 1      │
└─────────────────────────────────┴────────┘
shape: (288_204, 2)
┌─────────────────────┬───────┐
│ NU_LATITUDE         ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ -3.549302432472624  ┆ 1     │
│ -22.519023          ┆ 1     │
│ 0.03926753690401601 ┆ 1     │
│ -30.03520           ┆ 1     │
│ -20.2358796         ┆ 2     │
│ …                   ┆ …     │
│ -18.9205029         ┆ 2     │
│ -3.830978           ┆ 1     │
│ -6,23091            ┆ 1     │
│ -30.00200935        ┆ 1     │
│ -9.9846833          ┆ 1     │
└─────────────────────┴───────┘
shape: (287_366, 2)
┌─────────────────────┬───────┐
│ NU_LONGITUDE        ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ -48.192506975358214 ┆ 1     │
│ -42.65099912881851  ┆ 1     │

In [ ]:
# Diretório dos arquivos Parquet
PARQUET_DIR = f'{nome_pasta}/parquet'
arquivos = os.listdir(PARQUET_DIR)

# Criação de uma coluna de data para registrar a data de cada registro nas cada tabela
def adicionar_coluna_data(df, nome_arquivo):
    # Adiciona o ano_mes como uma nova coluna
    ano_mes = nome_arquivo.split('.')[0][-6:]
    ano = ano_mes[:4]
    mes = ano_mes[-2:]
    df = df.with_columns(
        pl.concat_str(
            pl.lit(ano),
            pl.lit('-'),
            pl.lit(mes),
            pl.lit('-01')
        ).alias('data_competencia')
    )
    return df

# Aplicando a função para adicionar a coluna de data
for arquivo in arquivos:
    df = pl.read_parquet(os.path.join(PARQUET_DIR, f'{arquivo}'))
    df = adicionar_coluna_data(df, arquivo)
    df.write_parquet(os.path.join(PARQUET_DIR, f'{arquivo}'))

In [15]:
TABELAS_INTERESSE = [
    'rlEstabComplementar',
    'tbAtributo',
    'tbEstabelecimento',
    'tbMunicipio',
    'tbEstado',
    'tbTipoUnidade',
    'tbTipoEstabelecimento',
    'tbAtividade',
    'tbAtividadeProfissional',
]

for file in os.listdir('cnes_2024/parquet'):
    for tabela in TABELAS_INTERESSE:
        df = pl.read_parquet(os.path.join('cnes_2024/parquet', file))
        print(f'🔍 Exibindo a contagem de registros de todas as colunas da tabela {file} -> Shape: ', df.shape, '\n')

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202401.parquet -> Shape:  (59133, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202402.parquet -> Shape:  (59187, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202403.parquet -> Shape:  (59236, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202404.parquet -> Shape:  (59405, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202405.parquet -> Shape:  (59481, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202406.parquet -> Shape:  (59548, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202407.parquet -> Shape:  (59637, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202408.parquet -> Shape:  (59722, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202409.parquet -> Shape:  (59789, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202410.parquet -> Shape:  (59736, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202411.parquet -> Shape:  (59745, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela rlEstabComplementar202412.parquet -> Shape:  (59787, 11)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202401.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202402.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202403.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202404.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202405.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202406.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)

🔍 Exibindo a contagem de registros de todas as colunas da tabela tbAtividade202407.parquet -> Shape:  (28, 5)


In [16]:
df = pl.read_parquet(os.path.join('cnes_2024/parquet', 'tbEstabelecimento202412.parquet'))
df_2 = pl.read_parquet(os.path.join('cnes_2024/parquet', 'tbEstabelecimento202405.parquet'))

In [18]:
set(df.columns) - set(df_2.columns)

{'ST_COWORKING'}

In [ ]:
# Concatena arquivos parquet por tabela base (sem data)
def concatenar_parquets_por_tabela():
    print("Concatenando arquivos por tabela base...")
    arquivos = os.listdir(PARQUET_DIR)
    tabelas_encontradas = {}

    # Agrupa arquivos por base
    for arquivo in arquivos:
        if not arquivo.endswith('.parquet'):
            continue
        nome_base = ''.join(filter(str.isalpha, arquivo.replace('.parquet', '')))
        tabelas_encontradas.setdefault(nome_base.lower(), []).append(arquivo)

    for base, arquivos_base in tabelas_encontradas.items():
        caminhos = [os.path.join(PARQUET_DIR, f) for f in arquivos_base]
        print(f'Concatenando {len(caminhos)} arquivos da tabela {base}...')

        if 'tbestabelecimento' in base.lower():
            dfs = []
            for c in caminhos:
                df = pl.read_parquet(c)
                if 'ST_COWORKING' in df.columns:
                    df = df.drop('ST_COWORKING')
                dfs.append(df)
            df_final = pl.concat(dfs, how='vertical_relaxed')

        else:
            dfs = [pl.read_parquet(c) for c in caminhos]
            df_final = pl.concat(dfs, how='vertical_relaxed')

        df_final.write_parquet(os.path.join('cnes_final', f'{base}_2024.parquet'))
        print(f'Tabela {base}_2024.parquet salva com sucesso!')

concatenar_parquets_por_tabela()

🔗 Concatenando arquivos por tabela base...
Concatenando 12 arquivos da tabela rlestabcomplementar...
Tabela rlestabcomplementar_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbatividade...
Tabela tbatividade_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbatividadeprofissional...
Tabela tbatividadeprofissional_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbatributo...
Tabela tbatributo_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbestabelecimento...
Tabela tbestabelecimento_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbestado...
Tabela tbestado_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbmunicipio...
Tabela tbmunicipio_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbtipoestabelecimento...
Tabela tbtipoestabelecimento_2024.parquet salva com sucesso!
Concatenando 12 arquivos da tabela tbtipounidade...
Tabela tbtipounidade_2024.parquet salva com sucesso!

In [27]:
# for file in os.listdir('cnes_final'):
#     print(file)
#     df = pl.read_parquet(os.path.join('cnes_final', file))
#     print(df.columns)

#     if 'CO_UNIDADE' in df.columns:
    
#         df_ativo = df['CO_UNIDADE', 'data_competencia'].group_by('CO_UNIDADE').agg(
#             pl.col('data_competencia').first().alias('data_primeiro_registro'),
#             pl.col('data_competencia').last().alias('data_ultimo_registro')
#         )

#         df = df.join(
#             df_ativo,
#             left_on='CO_UNIDADE',
#             right_on='CO_UNIDADE',
#             how='inner'
#         )

#         df = df.sort('data_ultimo_registro')

#         df_lazy = df.lazy()
#         df_deduplicado = df_lazy.unique(subset=["CO_UNIDADE"], keep='last').collect()

#         df = pl.read_parquet(f'cnes_2022/parquet/{file.replace('_2022', '202212')}')

#         print(f'🔍 Exibindo a contagem de registros da tabela {file} deduplicada -> Shape: ', df_deduplicado.shape, '\n')
#         print(f'🔍 Exibindo a contagem de registros da tabela {file} de dezembro -> Shape: ', df.shape, '\n')

In [ ]:
import os
import polars as pl

# Pastas
pasta_origem = 'cnes_final'
pasta_destino = 'cnes'
ano = '2022'
os.makedirs(pasta_destino, exist_ok=True)

# Listas de nomes das tabelas
tabelas_sem_mudanca = [
    'tbAtividade',
    'tbMunicipio',
    'tbEstado',
    'tbTipoUnidade',
    'tbTipoEstabelecimento',
    'tbAtributo',
]

tabelas_com_mudanca = [
    'rlEstabComplementar',
    'tbAtividadeProfissional',
]

# Função para processar
def processar_tabelas(lista_nomes, verificar_igual=True):
    for nome_tabela in lista_nomes:
        print(f'\n Processando {nome_tabela}...')

        # Lendo arquivo parquet
        caminho_parquet = f'{pasta_origem}/{nome_tabela.lower()}_{ano}.parquet'
        df = pl.read_parquet(caminho_parquet)

        if nome_tabela not in tabelas_com_mudanca:
            df = df.sort('data_competencia')

        # Drop duplicates
        df_unique = df.unique(subset=df.columns[:-1], keep='last')

        if verificar_igual:
            caminho_dezembro = f'cnes_2022/parquet/{nome_tabela}{ano}12.parquet'
            dezembro = pl.read_parquet(caminho_dezembro)
            print(f"Antes do drop duplicates: {df.shape}")
            print(f"Depois do drop duplicates: {df_unique.shape}")
            print(f"Tamanho do arquivo de dezembro: {dezembro.shape}")

            if df_unique.height == dezembro.height:
                print(f'Sem alterações. Salvando {nome_tabela} final com duplicatas removidas...')
            else:
                print(f'{nome_tabela} teve mudanças após deduplicação.')

        # Salvando
        caminho_destino = f'{pasta_destino}/{nome_tabela.lower()}_{ano}.parquet'
        df_unique.write_parquet(caminho_destino)
        print(f'{nome_tabela} salvo em {caminho_destino}')

# 🚀 Execução
processar_tabelas(tabelas_sem_mudanca, verificar_igual=True)
processar_tabelas(tabelas_com_mudanca, verificar_igual=False)

print("\n Todas as tabelas processadas com sucesso!")

🗂️ Processando tbAtividade...
Antes do drop duplicates: (336, 5)
Depois do drop duplicates: (28, 5)
Tamanho do arquivo de dezembro: (28, 5)
✅ Sem alterações. Salvando tbAtividade final com duplicatas removidas...
💾 tbAtividade salvo em cnes/tbatividade_2022.parquet

🗂️ Processando tbMunicipio...
Antes do drop duplicates: (67272, 14)
Depois do drop duplicates: (5606, 14)
Tamanho do arquivo de dezembro: (5606, 14)
✅ Sem alterações. Salvando tbMunicipio final com duplicatas removidas...
💾 tbMunicipio salvo em cnes/tbmunicipio_2022.parquet

🗂️ Processando tbEstado...
Antes do drop duplicates: (324, 4)
Depois do drop duplicates: (27, 4)
Tamanho do arquivo de dezembro: (27, 4)
✅ Sem alterações. Salvando tbEstado final com duplicatas removidas...
💾 tbEstado salvo em cnes/tbestado_2022.parquet

🗂️ Processando tbTipoUnidade...
Antes do drop duplicates: (468, 3)
Depois do drop duplicates: (39, 3)
Tamanho do arquivo de dezembro: (39, 3)
✅ Sem alterações. Salvando tbTipoUnidade final com duplicatas removidas...
💾 tbTipoUnidade salvo em cnes/tbtipounidade_2022.parquet

🗂️ Processando tbTipoEstabelecimento...
Antes do drop duplicates: (312, 4)
Depois do drop duplicates: (26, 4)
Tamanho do arquivo de dezembro: (26, 4)
✅ Sem alterações. Salvando tbTipoEstabelecimento final com duplicatas removidas...
💾 tbTipoEstabelecimento salvo em cnes/tbtipoestabelecimento_2022.parquet

🗂️ Processando tbAtributo...
Antes do drop duplicates: (288, 4)
Depois do drop duplicates: (24, 4)
Tamanho do arquivo de dezembro: (24, 4)
✅ Sem alterações. Salvando tbAtributo final com duplicatas removidas...
💾 tbAtributo salvo em cnes/tbatributo_2022.parquet

🗂️ Processando rlEstabComplementar...
💾 rlEstabComplementar salvo em cnes/rlestabcomplementar_2022.parquet

🗂️ Processando tbAtividadeProfissional...
💾 tbAtividadeProfissional salvo em cnes/tbatividadeprofissional_2022.parquet

✅ Todas as tabelas processadas com sucesso!

In [5]:
estabelecimento = pl.read_parquet('cnes_final/tbestabelecimento_2022.parquet') #ok
estab_complementar = pl.read_parquet('cnes_final/rlestabcomplementar_2022.parquet').sort('data_competencia', descending=False)
atividade_profissional = pl.read_parquet('cnes_final/tbatividadeprofissional_2022.parquet').sort('data_competencia', descending=False)

In [ ]:
# Seleção das colunas de interesse
estabelecimento = estabelecimento.select(
    [
        'CO_UNIDADE', 'CO_CNES', 'NU_CNPJ_MANTENEDORA', 'TP_PFPJ',
        'NIVEL_DEP', 'NO_RAZAO_SOCIAL', 'NO_FANTASIA', 'NO_LOGRADOURO',
        'NU_ENDERECO', 'NO_COMPLEMENTO', 'NO_BAIRRO', 'CO_CEP',
        'NU_CNPJ', 'CO_ATIVIDADE', 'TP_UNIDADE', 'CO_TURNO_ATENDIMENTO',
        'CO_ESTADO_GESTOR', 'CO_MUNICIPIO_GESTOR', 'CO_MOTIVO_DESAB',
        'TP_ESTAB_SEMPRE_ABERTO', 'CO_TIPO_UNIDADE', 'CO_TIPO_ESTABELECIMENTO',
        'CO_ATIVIDADE_PRINCIPAL', 'data_competencia'
    ]
)

# Agrupamento para obter primeira e ultima data de registro dos estabelecimentos
estabelecimento_datas = estabelecimento['CO_CNES', 'data_competencia'].group_by('CO_CNES').agg(
    pl.col('data_competencia').first().alias('data_primeiro_registro'),
    pl.col('data_competencia').last().alias('data_ultimo_registro')
)

# Junção do dataframe original com o dataframe de datas
estabelecimento = estabelecimento.join(
    estabelecimento_datas,
    left_on='CO_CNES',
    right_on='CO_CNES',
    how='inner'
)

# Ordenação do dataframe pela data do último registro
estabelecimento = estabelecimento.sort('data_ultimo_registro')

print("Total de estabelecimentos no ano de 2022: ", estabelecimento['CO_CNES'].n_unique())

# Deduplicação do dataframe, mantendo o último registro para cada CO_CNES
estabelecimento_lazy = estabelecimento.lazy()
estabelecimento_deduplicado = estabelecimento_lazy.unique(subset=["CO_CNES"], keep='last').collect()


deduplicado_22_ativo = estabelecimento_deduplicado.filter(
    (pl.col('CO_MOTIVO_DESAB') == '')
)['CO_CNES'].n_unique()

print("Estabelecimentos Ativos no ano de 2022: ", deduplicado_22_ativo)

df = pl.read_parquet('cnes_2022/parquet/tbEstabelecimento202212.parquet')

print("Total de establecimentos em dezembro de 2022: ", df['CO_CNES'].n_unique())

deduplicado2212_ativo = df.filter(
    (pl.col('CO_MOTIVO_DESAB') == '')
)['CO_CNES'].n_unique()

print("Estabelecimentos Ativos em dezembro de 2022: ", deduplicado2212_ativo)

print("Tamanho do arquivo de dezembro: ", df.shape)
print("Tamanho do arquivo de 2022: ", estabelecimento_deduplicado.shape)

Total de estabelecimentos no ano de 2022:  478055
Estabelecimentos Ativos no ano de 2022:  388399
Total de establecimentos em dezembro de 2022:  478047
Estabelecimentos Ativos em dezembro de 2022:  388398
Tamanho do arquivo de dezembro:  (478047, 55)
Tamanho do arquivo de 2022:  (478055, 26)

In [ ]:
estabelecimento_deduplicado.write_parquet('cnes/tbEstabelecimento_2022.parquet')

In [15]:
tabelas_com_mudanca = [
    'rlEstabComplementar',
    'tbAtividadeProfissional',
]

for nome_tabela in tabelas_com_mudanca:
    # Lendo arquivo parquet
    caminho_parquet = f'{pasta_origem}/{nome_tabela.lower()}_{ano}.parquet'
    df = pl.read_parquet(caminho_parquet)
    print(f'🔍 Exibindo a contagem de registros da tabela {nome_tabela} -> Shape: ', df.head(), '\n')

🔍 Exibindo a contagem de registros da tabela rlEstabComplementar -> Shape:  shape: (5, 11)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ CO_UNIDAD ┆ CO_LEITO ┆ CO_TIPO_L ┆ TP_ALTACO ┆ … ┆ TO_CHAR(D ┆ CO_USUARI ┆ TO_CHAR(D ┆ data_comp │
│ E         ┆ ---      ┆ EITO      ┆ MP        ┆   ┆ T_ATUALIZ ┆ O         ┆ T_ATUALIZ ┆ etencia   │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ACAO,'DD/ ┆ ---       ┆ ACAO_ORIG ┆ ---       │
│ str       ┆          ┆ str       ┆ str       ┆   ┆ MM/…      ┆ str       ┆ EM,…      ┆ str       │
│           ┆          ┆           ┆           ┆   ┆ ---       ┆           ┆ ---       ┆           │
│           ┆          ┆           ┆           ┆   ┆ str       ┆           ┆ str       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 310740566 ┆ 11       ┆ 1         ┆           ┆ … ┆ 15/04/201 ┆ SAOZINHA  ┆ 22/07/201 ┆ 2022-01-0 │
│ 1943      ┆          ┆           ┆           ┆   ┆ 9         ┆           ┆ 2         ┆ 1         │
│ 310740566 ┆ 15       ┆ 1         ┆           ┆ … ┆ 15/04/201 ┆ SAOZINHA  ┆ 22/07/201 ┆ 2022-01-0 │
│ 1943      ┆          ┆           ┆           ┆   ┆ 9         ┆           ┆ 2         ┆ 1         │
│ 313670312 ┆ 7        ┆ 7         ┆           ┆ … ┆ 16/08/201 ┆ CNESSCC   ┆ 22/07/201 ┆ 2022-01-0 │
│ 6277      ┆          ┆           ┆           ┆   ┆ 9         ┆           ┆ 2         ┆ 1         │
│ 291840919 ┆ 13       ┆ 1         ┆           ┆ … ┆ 31/03/201 ┆ ROSANGELA ┆ 03/04/201 ┆ 2022-01-0 │
│ 2484      ┆          ┆           ┆           ┆   ┆ 7         ┆           ┆ 7         ┆ 1         │
│ 240380720 ┆ 33       ┆ 2         ┆           ┆ … ┆ 18/04/201 ┆ FLORA     ┆ 05/04/201 ┆ 2022-01-0 │
│ 6933      ┆          ┆           ┆           ┆   ┆ 6         ┆           ┆ 3         ┆ 1         │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

🔍 Exibindo a contagem de registros da tabela tbAtividadeProfissional -> Shape:  shape: (5, 7)
┌────────┬───────────────┬──────────────┬──────────────┬──────────────┬─────────────┬──────────────┐
│ CO_CBO ┆ DS_ATIVIDADE_ ┆ TP_CLASSIFIC ┆ TP_CBO_SAUDE ┆ ST_CBO_REGUL ┆ NO_ANO_CMPT ┆ data_compete │
│ ---    ┆ PROFISSIONAL  ┆ ACAO_PROFISS ┆ ---          ┆ AMENTADO     ┆ ---         ┆ ncia         │
│ str    ┆ ---           ┆ IONAL        ┆ str          ┆ ---          ┆ str         ┆ ---          │
│        ┆ str           ┆ ---          ┆              ┆ str          ┆             ┆ str          │
│        ┆               ┆ str          ┆              ┆              ┆             ┆              │
╞════════╪═══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪══════════════╡
│ 513435 ┆ ATENDENTE DE  ┆              ┆ N            ┆ N            ┆             ┆ 2022-01-01   │
│        ┆ LANCHONETE    ┆              ┆              ┆              ┆             ┆              │
│ 513440 ┆ BARISTA       ┆              ┆ N            ┆ N            ┆             ┆ 2022-01-01   │
│ 513505 ┆ AUXILIAR NOS  ┆              ┆ N            ┆ N            ┆             ┆ 2022-01-01   │
│        ┆ SERVICOS DE   ┆              ┆              ┆              ┆             ┆              │
│        ┆ ALIME…        ┆              ┆              ┆              ┆             ┆              │
│ 513605 ┆ CHURRASQUEIRO ┆              ┆ N            ┆ N            ┆             ┆ 2022-01-01   │
│ 513610 ┆ PIZZAIOLO     ┆              ┆ N            ┆ N            ┆             ┆ 2022-01-01   │
└────────┴───────────────┴──────────────┴──────────────┴──────────────┴─────────────┴──────────────┘

In [72]:
import re
import unicodedata

def limpar_nome_coluna(coluna: str) -> str:
    """
    Limpa e padroniza nomes de colunas:
    - Remove HTML
    - Remove acentos e cedilha
    - Substitui espaços e hifens por _
    - Remove caracteres especiais
    - Remove múltiplos _
    - Deixa tudo em minúsculo
    """
    # Remove qualquer html tipo <span> ou <br>
    coluna = re.sub(r'<.*?>', '', coluna)

    # Normaliza unicode para remover acentos (acentos, cedilha etc.)
    coluna = unicodedata.normalize('NFKD', coluna)
    coluna = coluna.encode('ASCII', 'ignore').decode('utf-8')

    # Substitui espaços e hífens por underline
    coluna = re.sub(r'[\s\-]+', '_', coluna)

    # Remove tudo que não for letra, número ou underscore
    coluna = re.sub(r'[^a-zA-Z0-9_]', '', coluna)

    # Substitui múltiplos underlines por apenas um
    coluna = re.sub(r'_+', '_', coluna)

    # Remove underlines no início e no fim
    coluna = coluna.strip('_')

    # Converte pra minúsculo
    coluna = coluna.lower()

    return coluna


df = pl.read_excel(
        'data/cidades/al.xlsx'
    )

linhas = [0,1,2,3]

for linha in linhas:
    if 'Município [-]' in df.row(linha) or 'Municipio [-]' in df.row(linha):
        header = df.row(linha)
        linha_inicial = linha + 1
        print(linha_inicial)
        break

df = df[linha_inicial:]
df.columns = header
print(df.columns)


header = [
    'nome', 'codigo_municipio', 'gentilico',
    'prefeito', 'area_km2', 'populacao_residente',
    'densidade_demografica', 'escolarizacao_6_14',
    'idhm', 'mortalidade_infantil',
    'total_receitas_brutas_realizadas', 'total_despesas_brutas_empenhadas',
    'pib_per_capita'
]

df.columns = header

df = df.drop(['gentilico', 'prefeito'])

df = df.with_columns(
    pl.col('area_km2').str.replace('-', '0').cast(pl.Float64),
    pl.col('populacao_residente').str.replace('-', '0').cast(pl.Float64),
    pl.col('densidade_demografica').str.replace('-', '0').cast(pl.Float64),
    pl.col('escolarizacao_6_14').str.replace('-', '0').cast(pl.Float64),
    pl.col('idhm').str.replace('-', '0').cast(pl.Float64),
    pl.col('mortalidade_infantil').str.replace('-', '0').cast(pl.Float64),
    pl.col('total_receitas_brutas_realizadas').str.replace('-', '0').cast(pl.Float64),
    pl.col('total_despesas_brutas_empenhadas').str.replace('-', '0').cast(pl.Float64),
    pl.col('pib_per_capita').str.replace('-', '0').cast(pl.Float64)
)

# Remove linhas de rodapé (onde coluna "Município" está nula ou onde aparece 'Notas:')
if 'codigo_municipio' in df.columns:
    df = df.filter(pl.col('codigo_municipio').is_not_null() & ~pl.col('codigo_municipio').str.contains('Notas', literal=True))
elif 'codigo_municipio' in df.columns:
    df = df.filter(pl.col('codigo_municipio').is_not_null() & ~pl.col('codigo_municipio').str.contains('Notas', literal=True))

1
['Município [-]', 'Código [-]', 'Gentílico [-]', 'Prefeito [2025]', 'Área Territorial - km² [2023]', 'População residente - pessoas [2022]', 'Densidade demográfica - hab/km² [2022]', 'Escolarização <span>6 a 14 anos</span> - % [2010]', 'IDHM <span>Índice de desenvolvimento humano municipal</span> [2010]', 'Mortalidade infantil - óbitos por mil nascidos vivos [2022]', 'Total de receitas brutas realizadas - R$ [2022]', 'Total de despesas brutas empenhadas - R$ [2022]', 'PIB per capita - R$ [2021]']

In [73]:
df

shape: (102, 11)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ nome      ┆ codigo_mu ┆ area_km2 ┆ populacao ┆ … ┆ mortalida ┆ total_rec ┆ total_des ┆ pib_per_c │
│ ---       ┆ nicipio   ┆ ---      ┆ _resident ┆   ┆ de_infant ┆ eitas_bru ┆ pesas_bru ┆ apita     │
│ str       ┆ ---       ┆ f64      ┆ e         ┆   ┆ il        ┆ tas_reali ┆ tas_empen ┆ ---       │
│           ┆ str       ┆          ┆ ---       ┆   ┆ ---       ┆ zad…      ┆ had…      ┆ f64       │
│           ┆           ┆          ┆ f64       ┆   ┆ f64       ┆ ---       ┆ ---       ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆ f64       ┆ f64       ┆           │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Água      ┆ 2700102   ┆ 473.845  ┆ 19008.0   ┆ … ┆ 23.08     ┆ 1.1215e8  ┆ 1.3440e8  ┆ 10001.22  │
│ Branca    ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ Anadia    ┆ 2700201   ┆ 186.134  ┆ 13966.0   ┆ … ┆ 10.87     ┆ 8.4245e7  ┆ 9.6538e7  ┆ 14306.13  │
│ Arapiraca ┆ 2700300   ┆ 345.655  ┆ 234696.0  ┆ … ┆ 10.62     ┆ 1.0251e9  ┆ 1.0126e9  ┆ 25248.44  │
│ Atalaia   ┆ 2700409   ┆ 533.259  ┆ 37512.0   ┆ … ┆ 18.62     ┆ 2.3059e8  ┆ 2.5296905 ┆ 31559.62  │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ 9e8       ┆           │
│ Barra de  ┆ 2700508   ┆ 131.364  ┆ 16365.0   ┆ … ┆ 17.3      ┆ 9.7333e7  ┆ 1.0865e8  ┆ 16172.16  │
│ Santo     ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ Antônio   ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Taquarana ┆ 2709103   ┆ 153.841  ┆ 19032.0   ┆ … ┆ 10.75     ┆ 1.2763e8  ┆ 1.3809e8  ┆ 25335.01  │
│ Teotônio  ┆ 2709152   ┆ 299.222  ┆ 38053.0   ┆ … ┆ 12.22     ┆ 2.8577e8  ┆ 2.8125e8  ┆ 30461.61  │
│ Vilela    ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ Traipu    ┆ 2709202   ┆ 679.998  ┆ 23565.0   ┆ … ┆ 17.34     ┆ 1.4207e8  ┆ 1.6078e8  ┆ 10630.43  │
│ União dos ┆ 2709301   ┆ 420.376  ┆ 59280.0   ┆ … ┆ 16.45     ┆ 2.6585e8  ┆ 3.4974e8  ┆ 21467.05  │
│ Palmares  ┆           ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ Viçosa    ┆ 2709400   ┆ 365.644  ┆ 24092.0   ┆ … ┆ 6.1       ┆ 1.2480e8  ┆ 1.3432e8  ┆ 23158.1   │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [81]:
import re
import polars as pl
import unicodedata
from scripts.utils import criar_pastas

def limpar_nome_coluna(coluna: str) -> str:
    """
    Limpa e padroniza nomes de colunas:
    - Remove HTML
    - Remove acentos e cedilha
    - Substitui espaços e hifens por _
    - Remove caracteres especiais
    - Remove múltiplos _
    - Deixa tudo em minúsculo
    """
    # Remove qualquer html tipo <span> ou <br>
    coluna = re.sub(r'<.*?>', '', coluna)

    # Normaliza unicode para remover acentos (acentos, cedilha etc.)
    coluna = unicodedata.normalize('NFKD', coluna)
    coluna = coluna.encode('ASCII', 'ignore').decode('utf-8')

    # Substitui espaços e hífens por underline
    coluna = re.sub(r'[\s\-]+', '_', coluna)

    # Remove tudo que não for letra, número ou underscore
    coluna = re.sub(r'[^a-zA-Z0-9_]', '', coluna)

    # Substitui múltiplos underlines por apenas um
    coluna = re.sub(r'_+', '_', coluna)

    # Remove underlines no início e no fim
    coluna = coluna.strip('_')

    # Converte pra minúsculo
    coluna = coluna.lower()

    return coluna

def ler_cidades_ibge(path_csv):
    """
    Lê o CSV de cidades do IBGE, ignora cabeçalho e rodapé, limpa colunas e retorna um Polars DataFrame.
    """

    # Lê o CSV pulando as 2 primeiras linhas
    df = pl.read_excel(
        path_csv,
        read_options={"skip_rows": 1}
    )

    linhas = [0,1,2,3]

    for linha in linhas:
        if 'Município [-]' in df.row(linha) or 'Municipio [-]' in df.row(linha):
            header = df.row(linha)
            linha_inicial = linha + 1
            break

    df = df[linha_inicial:]
    df.columns = header

    header = [
        'nome', 'codigo_municipio', 'gentilico',
        'prefeito', 'area_km2', 'populacao_residente',
        'densidade_demografica', 'escolarizacao_6_14',
        'idhm', 'mortalidade_infantil',
        'total_receitas_brutas_realizadas', 'total_despesas_brutas_empenhadas',
        'pib_per_capita'
    ]

    df.columns = header

    df = df.drop(['gentilico', 'prefeito'])

    uf = path_csv.split('/')[-1].split('.')[0].upper()

    df = df.with_columns(
        pl.col('area_km2').str.replace('-', '0').cast(pl.Float64),
        pl.col('populacao_residente').str.replace('-', '0').cast(pl.Float64),
        pl.col('densidade_demografica').str.replace('-', '0').cast(pl.Float64),
        pl.col('escolarizacao_6_14').str.replace('-', '0').cast(pl.Float64),
        pl.col('idhm').str.replace('-', '0').cast(pl.Float64),
        pl.col('mortalidade_infantil').str.replace('-', '0').cast(pl.Float64),
        pl.col('total_receitas_brutas_realizadas').str.replace('-', '0').cast(pl.Float64),
        pl.col('total_despesas_brutas_empenhadas').str.replace('-', '0').cast(pl.Float64),
        pl.col('pib_per_capita').str.replace('-', '0').cast(pl.Float64),
        pl.lit(uf).alias('uf')
    )

    # Remove linhas de rodapé (onde coluna "Município" está nula ou onde aparece 'Notas:')
    if 'codigo_municipio' in df.columns:
        df = df.filter(pl.col('codigo_municipio').is_not_null() & ~pl.col('codigo_municipio').str.contains('Notas', literal=True))
    elif 'codigo_municipio' in df.columns:
        df = df.filter(pl.col('codigo_municipio').is_not_null() & ~pl.col('codigo_municipio').str.contains('Notas', literal=True))

    return df

def trata_dados_cidades():
    """
    Lê o CSV de cidades do IBGE, limpa e salva em Parquet.
    """
    criar_pastas(['data/cidades_final'])
    print("Lendo dados de cidades do IBGE...")
    
    dfs = []
    for file in os.listdir('data/cidades'):
        df = ler_cidades_ibge('data/cidades/' + file)
        dfs.append(df)
    
    df = pl.concat(dfs, how='vertical_relaxed')

    print("Salvando dados tratados...")
    
    df.write_parquet('data/cidades_final/cidades_ibge_2022.parquet')
    
    print("Arquivo de cidades tratado e salvo!")

In [82]:
trata_dados_cidades()

Pasta já existe: data/cidades_final
Lendo dados de cidades do IBGE...
Salvando dados tratados...
Arquivo de cidades tratado e salvo!

In [3]:
import polars as pl
import os

In [7]:
for file in os.listdir('data/ibge'):
    df = pl.read_excel('data/ibge/' + file)
    print(f'🔍 Exibindo a contagem de registros da tabela {file} -> Shape: ', df.shape, '\n')
    print(df.head())
    print('\n' + '-'*100 + '\n')

🔍 Exibindo a contagem de registros da tabela tabela10056 - frequencia escolar.xlsx -> Shape:  (5570, 9)

shape: (5, 9)
┌─────────┬─────────────────┬───────┬──────────┬───┬───────────┬────────────┬────────────┬─────────┐
│ codigo  ┆ nome            ┆ total ┆ 0_3_anos ┆ … ┆ 6_14_anos ┆ 15_17_anos ┆ 18_24_anos ┆ 25_mais │
│ ---     ┆ ---             ┆ ---   ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---        ┆ ---     │
│ str     ┆ str             ┆ f64   ┆ str      ┆   ┆ f64       ┆ f64        ┆ f64        ┆ f64     │
╞═════════╪═════════════════╪═══════╪══════════╪═══╪═══════════╪════════════╪════════════╪═════════╡
│ 1100015 ┆ Alta Floresta   ┆ 36.32 ┆ 10.95    ┆ … ┆ 97.44     ┆ 84.23      ┆ 34.23      ┆ 22.33   │
│         ┆ D'Oeste (RO)    ┆       ┆          ┆   ┆           ┆            ┆            ┆         │
│ 1100023 ┆ Ariquemes (RO)  ┆ 26.96 ┆ 16.61    ┆ … ┆ 98.12     ┆ 79.66      ┆ 28.59      ┆ 6.38    │
│ 1100031 ┆ Cabixi (RO)     ┆ 24.15 ┆ 18.12    ┆ … ┆ 99.55     ┆ 91.12      ┆ 18.93      ┆ 3.09    │
│ 1100049 ┆ Cacoal (RO)     ┆ 30.72 ┆ 13.27    ┆ … ┆ 98.16     ┆ 90.67      ┆ 38.04      ┆ 12.26   │
│ 1100056 ┆ Cerejeiras (RO) ┆ 23.98 ┆ 16.37    ┆ … ┆ 99.35     ┆ 90.99      ┆ 21.14      ┆ 3.61    │
└─────────┴─────────────────┴───────┴──────────┴───┴───────────┴────────────┴────────────┴─────────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela10061 - taxa_populacao_nivel_instrucao.xlsx -> Shape:  (5570, 6)

shape: (5, 6)
┌─────────┬─────────────────┬─────────────────┬─────────────────┬─────────────────┬────────────────┐
│ codigo  ┆ nome            ┆ sem_instrucao_f ┆ fundamental_com ┆ medio_completo_ ┆ superior_compl │
│ ---     ┆ ---             ┆ undamental_inco ┆ pleto_medio_inc ┆ superior_incomp ┆ eto            │
│ str     ┆ str             ┆ …               ┆ …               ┆ …               ┆ ---            │
│         ┆                 ┆ ---             ┆ ---             ┆ ---             ┆ f64            │
│         ┆                 ┆ f64             ┆ f64             ┆ f64             ┆                │
╞═════════╪═════════════════╪═════════════════╪═════════════════╪═════════════════╪════════════════╡
│ 1100015 ┆ Alta Floresta   ┆ 54.47           ┆ 16.97           ┆ 19.09           ┆ 9.47           │
│         ┆ D'Oeste (RO)    ┆                 ┆                 ┆                 ┆                │
│ 1100023 ┆ Ariquemes (RO)  ┆ 37.21           ┆ 15.99           ┆ 32.33           ┆ 14.46          │
│ 1100031 ┆ Cabixi (RO)     ┆ 53.41           ┆ 10.24           ┆ 25.81           ┆ 10.54          │
│ 1100049 ┆ Cacoal (RO)     ┆ 36.92           ┆ 16.74           ┆ 28.74           ┆ 17.6           │
│ 1100056 ┆ Cerejeiras (RO) ┆ 40.2            ┆ 14.74           ┆ 28.34           ┆ 16.73          │
└─────────┴─────────────────┴─────────────────┴─────────────────┴─────────────────┴────────────────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela10062 - anos_de_estudo.xlsx -> Shape:  (5571, 7)

shape: (5, 7)
┌─────────┬────────────────────────────┬───────┬───────┬───────┬───────┬─────────┐
│ codigo  ┆ nome                       ┆ total ┆ 11_14 ┆ 15_17 ┆ 18_24 ┆ 25_mais │
│ ---     ┆ ---                        ┆ ---   ┆ ---   ┆ ---   ┆ ---   ┆ ---     │
│ str     ┆ str                        ┆ f64   ┆ f64   ┆ f64   ┆ f64   ┆ f64     │
╞═════════╪════════════════════════════╪═══════╪═══════╪═══════╪═══════╪═════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 7.1   ┆ 6.3   ┆ 8.3   ┆ 10.4  ┆ 6.5     │
│ 1100023 ┆ Ariquemes (RO)             ┆ 8.9   ┆ 6.3   ┆ 8.9   ┆ 11.2  ┆ 8.7     │
│ 1100031 ┆ Cabixi (RO)                ┆ 7.3   ┆ 6.1   ┆ 8.5   ┆ 10.9  ┆ 7.0     │
│ 1100049 ┆ Cacoal (RO)                ┆ 9.1   ┆ 6.5   ┆ 9.0   ┆ 11.3  ┆ 8.9     │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 8.6   ┆ 6.5   ┆ 8.6   ┆ 11.2  ┆ 8.4     │
└─────────┴────────────────────────────┴───────┴───────┴───────┴───────┴─────────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela6803 - taxa_rede_esgoto.xlsx -> Shape:  (5570, 4)

shape: (5, 4)
┌─────────┬────────────────────────────┬───────┬───────┐
│ codigo  ┆ nome                       ┆ nao   ┆ sim   │
│ ---     ┆ ---                        ┆ ---   ┆ ---   │
│ str     ┆ str                        ┆ f64   ┆ f64   │
╞═════════╪════════════════════════════╪═══════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 66.26 ┆ 33.73 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 34.64 ┆ 65.37 │
│ 1100031 ┆ Cabixi (RO)                ┆ 50.64 ┆ 49.37 │
│ 1100049 ┆ Cacoal (RO)                ┆ 17.47 ┆ 82.54 │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 31.93 ┆ 68.07 │
└─────────┴────────────────────────────┴───────┴───────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela6892 - taxa_coleta_lixo.xlsx -> Shape:  (5571, 3)

shape: (5, 3)
┌─────────┬────────────────────────────┬──────────────┐
│ codigo  ┆ nome                       ┆ pct_coletado │
│ ---     ┆ ---                        ┆ ---          │
│ str     ┆ str                        ┆ f64          │
╞═════════╪════════════════════════════╪══════════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 61.48        │
│ 1100023 ┆ Ariquemes (RO)             ┆ 90.42        │
│ 1100031 ┆ Cabixi (RO)                ┆ 61.06        │
│ 1100049 ┆ Cacoal (RO)                ┆ 85.66        │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 87.04        │
└─────────┴────────────────────────────┴──────────────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela9514 - taxa_distribuicao_etaria.xlsx -> Shape:  (5570, 3)

shape: (5, 3)
┌─────────┬────────────────────────────┬─────────────┐
│ codigo  ┆ nome                       ┆ pct_60_mais │
│ ---     ┆ ---                        ┆ ---         │
│ str     ┆ str                        ┆ f64         │
╞═════════╪════════════════════════════╪═════════════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 14.53       │
│ 1100023 ┆ Ariquemes (RO)             ┆ 11.54       │
│ 1100031 ┆ Cabixi (RO)                ┆ 19.23       │
│ 1100049 ┆ Cacoal (RO)                ┆ 13.34       │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 14.69       │
└─────────┴────────────────────────────┴─────────────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela9543 - taxa_de_alfabetizacao.xlsx -> Shape:  (5570, 3)

shape: (5, 3)
┌─────────┬────────────────────────────┬───────┐
│ codigo  ┆ nome                       ┆ total │
│ ---     ┆ ---                        ┆ ---   │
│ str     ┆ str                        ┆ f64   │
╞═════════╪════════════════════════════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 91.59 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 94.08 │
│ 1100031 ┆ Cabixi (RO)                ┆ 89.82 │
│ 1100049 ┆ Cacoal (RO)                ┆ 93.71 │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 92.15 │
└─────────┴────────────────────────────┴───────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela9884 - pop res favela.xlsx -> Shape:  (656, 3)

shape: (5, 3)
┌─────────┬──────────────────────┬───────┐
│ codigo  ┆ nome                 ┆ total │
│ ---     ┆ ---                  ┆ ---   │
│ str     ┆ str                  ┆ i64   │
╞═════════╪══════════════════════╪═══════╡
│ 1100049 ┆ Cacoal (RO)          ┆ 543   │
│ 1100106 ┆ Guajará-Mirim (RO)   ┆ 2943  │
│ 1100205 ┆ Porto Velho (RO)     ┆ 79809 │
│ 1200104 ┆ Brasiléia (AC)       ┆ 3854  │
│ 1200203 ┆ Cruzeiro do Sul (AC) ┆ 14687 │
└─────────┴──────────────────────┴───────┘

----------------------------------------------------------------------------------------------------

🔍 Exibindo a contagem de registros da tabela tabela9923 - taxa_situacao_domicilio.xlsx -> Shape:  (5570, 4)

shape: (5, 4)
┌─────────┬────────────────────────────┬────────┬───────┐
│ codigo  ┆ nome                       ┆ urbana ┆ rural │
│ ---     ┆ ---                        ┆ ---    ┆ ---   │
│ str     ┆ str                        ┆ f64    ┆ f64   │
╞═════════╪════════════════════════════╪════════╪═══════╡
│ 1100015 ┆ Alta Floresta D'Oeste (RO) ┆ 60.35  ┆ 39.65 │
│ 1100023 ┆ Ariquemes (RO)             ┆ 86.7   ┆ 13.3  │
│ 1100031 ┆ Cabixi (RO)                ┆ 53.19  ┆ 46.81 │
│ 1100049 ┆ Cacoal (RO)                ┆ 82.76  ┆ 17.24 │
│ 1100056 ┆ Cerejeiras (RO)            ┆ 88.84  ┆ 11.16 │
└─────────┴────────────────────────────┴────────┴───────┘

----------------------------------------------------------------------------------------------------