In [2]:
import pandas as pd
import polars as pl

In [53]:
# Dicionário contendo os nomes das tabelas e arquivos CSV
tabelas = {
    'estabelecimento': 'tbEstabelecimento202409.csv',
    'tipo_estabelecimento': 'tbTipoEstabelecimento202409.csv',
    'atividade_principal': 'tbAtividade202409.csv',
    'natureza_juridica': 'tbNaturezaJuridica202409.csv',
    'motivo_desativacao': 'tbMotivoDesativacao202409.csv',
    'cod_municipio': 'tbMunicipio202409.csv'
}

# Caminho base onde estão localizados os arquivos CSV
file_path = "certeza_de_uso/BASE_DE_DADOS_CNES_202409/"

# Dicionário para armazenar os dataframes
dataframes = {}

# Loop para carregar cada CSV e armazenar no dicionário
for var, tabela in tabelas.items():
    try:
        # Carregar o CSV usando Polars
        df = pl.read_csv(
            file_path + tabela,
            separator=';',          # Delimitador do CSV
            encoding='utf8-lossy',  # Codificação com fallback para caracteres problemáticos
            has_header=True,        # Assume que a primeira linha é o cabeçalho
            ignore_errors=True      # Ignora possíveis erros de parsing
        )
        # Armazena o dataframe no dicionário usando a chave do loop
        dataframes[var] = df
        print(f"Carregado: {var} com {df.shape[0]} linhas e {df.shape[1]} colunas")
    
    except Exception as e:
        print(f"Erro ao carregar o arquivo {tabela}: {e}")

print(f"Tamanho do datraframe de estabelecimentos: {dataframes['estabelecimento'].shape}")

dataframes['tipo_estabelecimento'] = dataframes['tipo_estabelecimento'].with_columns(
    pl.col('CO_TIPO_ESTABELECIMENTO').cast(pl.Utf8)
)

dataframes['motivo_desativacao'] = dataframes['motivo_desativacao'].with_columns(
    pl.col('CD_MOTIVO_DESAB').cast(pl.Utf8)
)

# Realizar os joins de forma incremental usando 'left' join
df = dataframes['estabelecimento']

df = df.join(
    dataframes['tipo_estabelecimento'], 
    on='CO_TIPO_ESTABELECIMENTO', 
    how='left'
)

df = df.join(
    dataframes['atividade_principal'], 
    on='CO_ATIVIDADE', 
    how='left'
)

df = df.join(
    dataframes['natureza_juridica'], 
    on='CO_NATUREZA_JUR', 
    how='left'
)

df = df.join(
    dataframes['motivo_desativacao'], 
    left_on='CO_MOTIVO_DESAB', 
    right_on='CD_MOTIVO_DESAB', 
    how='left'
)

df = df.join(
    dataframes['cod_municipio'], 
    left_on='CO_MUNICIPIO_GESTOR', 
    right_on='CO_MUNICIPIO', 
    how='left'
)

print(f"Dataframe final após os joins: {df.shape}")

Carregado: estabelecimento com 548991 linhas e 56 colunas
Carregado: tipo_estabelecimento com 26 linhas e 3 colunas
Carregado: atividade_principal com 28 linhas e 4 colunas
Carregado: natureza_juridica com 100 linhas e 2 colunas
Carregado: motivo_desativacao com 14 linhas e 2 colunas
Carregado: cod_municipio com 5606 linhas e 13 colunas
Tamanho do datraframe de estabelecimentos: (548991, 56)
Dataframe final após os joins: (548991, 75)

In [65]:
# Análise das tabelas carregadas (exceto 'estabelecimento')
for tabela, df in dataframes.items():
    if tabela != 'estabelecimento':
        print(f"\n-------------------------- {tabela} ------------------------------------------------")
        # Exibir contagem de valores por coluna
        for col in df.columns:
            print(f"Coluna: {col}")
            print(df[col].value_counts(), "\n")

-------------------------- tipo_estabelecimento ------------------------------------------------
Coluna: CO_TIPO_ESTABELECIMENTO
shape: (26, 2)
┌─────────────────────────┬───────┐
│ CO_TIPO_ESTABELECIMENTO ┆ count │
│ ---                     ┆ ---   │
│ str                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 15                      ┆ 1     │
│ 4                       ┆ 1     │
│ 12                      ┆ 1     │
│ 18                      ┆ 1     │
│ 3                       ┆ 1     │
│ …                       ┆ …     │
│ 24                      ┆ 1     │
│ 14                      ┆ 1     │
│ 11                      ┆ 1     │
│ 23                      ┆ 1     │
│ 8                       ┆ 1     │
└─────────────────────────┴───────┘

Coluna: DS_TIPO_ESTABELECIMENTO
shape: (26, 2)
┌─────────────────────────────────┬───────┐
│ DS_TIPO_ESTABELECIMENTO         ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ UNIDADE DE REABILITACAO         ┆ 1     │
│ UNIDADE DE VIGILANCIA DE ZOONO… ┆ 1     │
│ CENTRO DE REFERENCIA EM SAUDE … ┆ 1     │
│ OUTROS                          ┆ 1     │
│ CENTRO DE IMUNIZACAO            ┆ 1     │
│ …                               ┆ …     │
│ CENTRAL DE REGULACAO            ┆ 1     │
│ CENTRAL DE ABASTECIMENTO        ┆ 1     │
│ UNIDADE DE ATENCAO PSICOSSOCIA… ┆ 1     │
│ CENTRAL DE TRANSPLANTE          ┆ 1     │
│ LABORATORIO DE SAUDE PUBLICA    ┆ 1     │
└─────────────────────────────────┴───────┘

Coluna: DS_CONCEITO_TIPO
shape: (1, 2)
┌──────────────────┬───────┐
│ DS_CONCEITO_TIPO ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│                  ┆ 26    │
└──────────────────┴───────┘


-------------------------- atividade_principal ------------------------------------------------
Coluna: CO_GRUPO_ATIVIDADE
shape: (5, 2)
┌────────────────────┬───────┐
│ CO_GRUPO_ATIVIDADE ┆ count │
│ ---                ┆ ---   │
│ i64                ┆ u32   │
╞════════════════════╪═══════╡
│ 3                  ┆ 4     │
│ 1                  ┆ 17    │
│ 4                  ┆ 2     │
│ 0                  ┆ 1     │
│ 2                  ┆ 4     │
└────────────────────┴───────┘

Coluna: CO_ATIVIDADE
shape: (28, 2)
┌──────────────┬───────┐
│ CO_ATIVIDADE ┆ count │
│ ---          ┆ ---   │
│ i64          ┆ u32   │
╞══════════════╪═══════╡
│ 5            ┆ 1     │
│ 15           ┆ 1     │
│ 26           ┆ 1     │
│ 9            ┆ 1     │
│ 6            ┆ 1     │
│ …            ┆ …     │
│ 12           ┆ 1     │
│ 27           ┆ 1     │
│ 0            ┆ 1     │
│ 1            ┆ 1     │
│ 8            ┆ 1     │
└──────────────┴───────┘

Coluna: DS_ATIVIDADE
shape: (28, 2)
┌─────────────────────────────────┬───────┐
│ DS_ATIVIDADE                    ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ LOGISTICA DE ORGAOS, TECIDOS E… ┆ 1     │
│ ATENCAO BASICA                  ┆ 1     │
│ ADMINISTRACAO                   ┆ 1     │
│ ENTREGA/DISPENSACAO DE MEDICAM… ┆ 1     │
│ ATENCAO DOMICILIAR              ┆ 1     │
│ …                               ┆ …     │
│ ASSISTENCIA INTERMEDIARIA       ┆ 1     │
│ CONCESSAO, MANUTENCAO E ADAPTA… ┆ 1     │
│ CONSULTA AMBULATORIAL           ┆ 1     │
│ IMUNIZACAO                      ┆ 1     │
│ ANALISES LABORATORIAIS DE VIGI… ┆ 1     │
└─────────────────────────────────┴───────┘

Coluna: DS_CONCEITO_ATIVIDADE
shape: (28, 2)
┌─────────────────────────────────┬───────┐
│ DS_CONCEITO_ATIVIDADE           ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ Conjunto de a��es relativas ao… ┆ 1     │
│ A��es e servi�os prestados de … ┆ 1     │
│ Sem Conceito                    ┆ 1     │
│ Servi�o de fabrica��o e produ�… ┆ 1     │
│ Conjunto de cuidados ou tratam… ┆ 1     │
│ …                               ┆ …     │
│ A��es e servi�os de vigil�ncia… ┆ 1     │
│ Compreende a organiza��o, o co… ┆ 1     │
│ Servi�os que utilizam tecnolog… ┆ 1     │
│ Compreende o armazenamento e d… ┆ 1     │
│ Servi�os que visam alojar temp… ┆ 1     │
└─────────────────────────────────┴───────┘


-------------------------- natureza_juridica ------------------------------------------------
Coluna: CO_NATUREZA_JUR
shape: (100, 2)
┌─────────────────┬───────┐
│ CO_NATUREZA_JUR ┆ count │
│ ---             ┆ ---   │
│ i64             ┆ u32   │
╞═════════════════╪═══════╡
│ 5010            ┆ 1     │
│ 2330            ┆ 1     │
│ 2321            ┆ 1     │
│ 3069            ┆ 1     │
│ 1082            ┆ 1     │
│ …               ┆ …     │
│ 1163            ┆ 1     │
│ 1058            ┆ 1     │
│ 4120            ┆ 1     │
│ 5037            ┆ 1     │
│ 2348            ┆ 1     │
└─────────────────┴───────┘

Coluna: DS_NATUREZA_JUR
shape: (100, 2)
┌─────────────────────────────────┬───────┐
│ DS_NATUREZA_JUR                 ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ EMPRESA INDIVIDUAL DE RESPONSA… ┆ 1     │
│ ORGAO DE DIRECAO REGIONAL DE P… ┆ 1     │
│ GRUPO DE SOCIEDADES             ┆ 1     │
│ ORGAO PUBLICO DO PODER JUDICIA… ┆ 1     │
│ CLUBEFUNDO DE INVESTIMENTO      ┆ 1     │
│ …                               ┆ …     │
│ FUNDO PRIVADO                   ┆ 1     │
│ CONSORCIO DE SOCIEDADES         ┆ 1     │
│ ORGAO PUBLICO DO PODER LEGISLA… ┆ 1     │
│ PRODUTOR RURAL (PESSOA FISICA)  ┆ 1     │
│ FUNDO PUBLICO DA ADMINISTRA��O… ┆ 1     │
└─────────────────────────────────┴───────┘


-------------------------- motivo_desativacao ------------------------------------------------
Coluna: CD_MOTIVO_DESAB
shape: (14, 2)
┌─────────────────┬───────┐
│ CD_MOTIVO_DESAB ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ 2               ┆ 1     │
│ 7               ┆ 1     │
│ 9               ┆ 1     │
│ 14              ┆ 1     │
│ 10              ┆ 1     │
│ …               ┆ …     │
│ 8               ┆ 1     │
│ 3               ┆ 1     │
│ 13              ┆ 1     │
│ 4               ┆ 1     │
│ 12              ┆ 1     │
└─────────────────┴───────┘

Coluna: DS_MOTIVO_DESAB
shape: (14, 2)
┌─────────────────────────────────┬───────┐
│ DS_MOTIVO_DESAB                 ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ ALTERACAO DE ATIVIDADE PRINCIP… ┆ 1     │
│ DESATIVADO DEFINITIVAMENTE POR… ┆ 1     │
│ DESATIVADO - OUTROS             ┆ 1     │
│ PELO GESTOR POR INCONSISTENCIA… ┆ 1     │
│ DESATIVADO TEMPORARIAMENTE POR… ┆ 1     │
│ …                               ┆ …     │
│ PELO GESTOR POR DESATUALIZACAO… ┆ 1     │
│ DESATIVADO TEMPORARIAMENTE POR… ┆ 1     │
│ AUTOMATICAMENTE POR NAO ATUALI… ┆ 1     │
│ ALTERACAO DO REGIME DE DIREITO… ┆ 1     │
│ CADASTRADO INDEVIDAMENTE        ┆ 1     │
└─────────────────────────────────┴───────┘


-------------------------- cod_municipio ------------------------------------------------
Coluna: CO_MUNICIPIO
shape: (5_606, 2)
┌──────────────┬───────┐
│ CO_MUNICIPIO ┆ count │
│ ---          ┆ ---   │
│ i64          ┆ u32   │
╞══════════════╪═══════╡
│ 313375       ┆ 1     │
│ 412030       ┆ 1     │
│ 430540       ┆ 1     │
│ 351260       ┆ 1     │
│ 251260       ┆ 1     │
│ …            ┆ …     │
│ 420310       ┆ 1     │
│ 510642       ┆ 1     │
│ 150200       ┆ 1     │
│ 315930       ┆ 1     │
│ 432010       ┆ 1     │
└──────────────┴───────┘

Coluna: NO_MUNICIPIO
shape: (5_315, 2)
┌────────────────────────┬───────┐
│ NO_MUNICIPIO           ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ LAGOA DA PRATA         ┆ 1     │
│ MAE DO RIO             ┆ 1     │
│ PATOS DE MINAS         ┆ 1     │
│ CASEIROS               ┆ 1     │
│ LAGOA GRANDE           ┆ 2     │
│ …                      ┆ …     │
│ JURUENA                ┆ 1     │
│ GUARACIAMA             ┆ 1     │
│ LUIS EDUARDO MAGALHAES ┆ 1     │
│ SANTA JULIANA          ┆ 1     │
│ AREADO                 ┆ 1     │
└────────────────────────┴───────┘

Coluna: CO_SIGLA_ESTADO
shape: (30, 2)
┌─────────────────┬───────┐
│ CO_SIGLA_ESTADO ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ RJ              ┆ 92    │
│ SE              ┆ 75    │
│ ES              ┆ 78    │
│ RR              ┆ 15    │
│ MS              ┆ 79    │
│ …               ┆ …     │
│ AP              ┆ 16    │
│ RS              ┆ 497   │
│ MG              ┆ 853   │
│ PE              ┆ 185   │
│ UF              ┆ 1     │
└─────────────────┴───────┘

Coluna: TP_CADASTRO
shape: (2, 2)
┌─────────────┬───────┐
│ TP_CADASTRO ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ N           ┆ 32    │
│ S           ┆ 5574  │
└─────────────┴───────┘

Coluna: TP_PACTO
shape: (2, 2)
┌──────────┬───────┐
│ TP_PACTO ┆ count │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│          ┆ 1     │
│ S        ┆ 5605  │
└──────────┴───────┘

Coluna: TP_ENVIA
shape: (2, 2)
┌──────────┬───────┐
│ TP_ENVIA ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 1        ┆ 5573  │
│ 3        ┆ 33    │
└──────────┴───────┘

Coluna: TP_ENVIA_CNES
shape: (2, 2)
┌───────────────┬───────┐
│ TP_ENVIA_CNES ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ S             ┆ 5573  │
│ N             ┆ 33    │
└───────────────┴───────┘

Coluna: TP_CIB_SAS
shape: (3, 2)
┌────────────┬───────┐
│ TP_CIB_SAS ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ S          ┆ 5604  │
│            ┆ 1     │
│ N          ┆ 1     │
└────────────┴───────┘

Coluna: TP_PLENO_ORIGEM
shape: (3, 2)
┌─────────────────┬───────┐
│ TP_PLENO_ORIGEM ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ N               ┆ 4920  │
│ S               ┆ 684   │
│                 ┆ 2     │
└─────────────────┴───────┘

Coluna: TP_MAC
shape: (1, 2)
┌────────┬───────┐
│ TP_MAC ┆ count │
│ ---    ┆ ---   │
│ str    ┆ u32   │
╞════════╪═══════╡
│ S      ┆ 5606  │
└────────┴───────┘

Coluna: NU_POPULACAO
shape: (428, 2)
┌──────────────┬───────┐
│ NU_POPULACAO ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ 18202        ┆ 1     │
│ 60558        ┆ 1     │
│ 51223        ┆ 1     │
│ 1216         ┆ 1     │
│ 16864        ┆ 1     │
│ …            ┆ …     │
│ 4458         ┆ 2     │
│ 48221        ┆ 1     │
│ 39387        ┆ 1     │
│ 50047        ┆ 1     │
│ 3602         ┆ 1     │
└──────────────┴───────┘

Coluna: NU_DENSIDADE
shape: (10, 2)
┌──────────────┬───────┐
│ NU_DENSIDADE ┆ count │
│ ---          ┆ ---   │
│ str          ┆ u32   │
╞══════════════╪═══════╡
│ 4            ┆ 100   │
│ 7            ┆ 64    │
│              ┆ 604   │
│ 1            ┆ 4253  │
│ 9            ┆ 71    │
│ 5            ┆ 84    │
│ 3            ┆ 143   │
│ 2            ┆ 168   │
│ 6            ┆ 61    │
│ 8            ┆ 58    │
└──────────────┴───────┘

Coluna: CMTP_INICIO_MAC
shape: (8, 2)
┌─────────────────┬───────┐
│ CMTP_INICIO_MAC ┆ count │
│ ---             ┆ ---   │
│ i64             ┆ u32   │
╞═════════════════╪═══════╡
│ 102018          ┆ 1403  │
│ 52018           ┆ 41    │
│ 42018           ┆ 12    │
│ 92018           ┆ 4     │
│ 72018           ┆ 2     │
│ 32018           ┆ 4120  │
│ 62018           ┆ 16    │
│ 82018           ┆ 8     │
└─────────────────┴───────┘

In [56]:
df.filter(
    pl.col('NO_MUNICIPIO') == 'PARANAGUA'
).head()

shape: (5, 75)
┌─────────────┬─────────┬────────────┬─────────┬───┬────────┬────────────┬────────────┬────────────┐
│ CO_UNIDADE  ┆ CO_CNES ┆ NU_CNPJ_MA ┆ TP_PFPJ ┆ … ┆ TP_MAC ┆ NU_POPULAC ┆ NU_DENSIDA ┆ CMTP_INICI │
│ ---         ┆ ---     ┆ NTENEDORA  ┆ ---     ┆   ┆ ---    ┆ AO         ┆ DE         ┆ O_MAC      │
│ i64         ┆ i64     ┆ ---        ┆ i64     ┆   ┆ str    ┆ ---        ┆ ---        ┆ ---        │
│             ┆         ┆ str        ┆         ┆   ┆        ┆ str        ┆ str        ┆ i64        │
╞═════════════╪═════════╪════════════╪═════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 41182095530 ┆ 9553088 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 88          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 41182098143 ┆ 9814302 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 02          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 41182099201 ┆ 9920145 ┆ 7601745800 ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 45          ┆         ┆ 0115       ┆         ┆   ┆        ┆            ┆            ┆            │
│ 41182001803 ┆ 180351  ┆            ┆ 1       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 51          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 41182099574 ┆ 9957472 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 72          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
└─────────────┴─────────┴────────────┴─────────┴───┴────────┴────────────┴────────────┴────────────┘

In [61]:
df['CO_SIGLA_ESTADO'].value_counts().sort('count')

shape: (27, 2)
┌─────────────────┬────────┐
│ CO_SIGLA_ESTADO ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u32    │
╞═════════════════╪════════╡
│ AP              ┆ 1169   │
│ RR              ┆ 1461   │
│ AC              ┆ 1760   │
│ TO              ┆ 3110   │
│ AM              ┆ 4029   │
│ …               ┆ …      │
│ PR              ┆ 38763  │
│ RS              ┆ 42176  │
│ RJ              ┆ 49962  │
│ MG              ┆ 67583  │
│ SP              ┆ 133518 │
└─────────────────┴────────┘

In [64]:
df['NO_MUNICIPIO'].value_counts().sort('count', descending=True).head(20)

shape: (20, 2)
┌─────────────────────┬───────┐
│ NO_MUNICIPIO        ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ SAO PAULO           ┆ 37631 │
│ RIO DE JANEIRO      ┆ 24878 │
│ BRASILIA            ┆ 10923 │
│ BELO HORIZONTE      ┆ 9682  │
│ CURITIBA            ┆ 9242  │
│ …                   ┆ …     │
│ BELEM               ┆ 2949  │
│ JOAO PESSOA         ┆ 2814  │
│ FLORIANOPOLIS       ┆ 2769  │
│ SAO JOSE DOS CAMPOS ┆ 2708  │
│ NATAL               ┆ 2686  │
└─────────────────────┴───────┘

In [66]:
df.group_by(
    pl.col('NO_MUNICIPIO')
).agg(
    pl.col('NU_POPULACAO')
)

shape: (5_315, 2)
┌──────────────────┬──────────────┐
│ NO_MUNICIPIO     ┆ NU_POPULACAO │
│ ---              ┆ ---          │
│ str              ┆ list[str]    │
╞══════════════════╪══════════════╡
│ ALVARES MACHADO  ┆ [""]         │
│ BACURITUBA       ┆ [""]         │
│ GUAJARA-MIRIM    ┆ ["42694"]    │
│ PRESIDENTE ALVES ┆ [""]         │
│ JANAUBA          ┆ [""]         │
│ …                ┆ …            │
│ ITAPEVA          ┆ ["", ""]     │
│ SAO JOSE DO POVO ┆ [""]         │
│ LARANJAL DO JARI ┆ ["37626"]    │
│ JURANDA          ┆ [""]         │
│ SAO LEOPOLDO     ┆ [""]         │
└──────────────────┴──────────────┘

In [35]:
dataframes['motivo_desativacao'].with_columns(
    pl.col('CD_MOTIVO_DESAB').cast(pl.Utf8)
)

shape: (14, 2)
┌─────────────────┬─────────────────────────────────┐
│ CD_MOTIVO_DESAB ┆ DS_MOTIVO_DESAB                 │
│ ---             ┆ ---                             │
│ str             ┆ str                             │
╞═════════════════╪═════════════════════════════════╡
│ 1               ┆ DESATIVADO TEMPORARIAMENTE PEL… │
│ 3               ┆ DESATIVADO TEMPORARIAMENTE POR… │
│ 2               ┆ DESATIVADO TEMPORARIAMENTE POR… │
│ 4               ┆ DESATIVADO - OUTROS             │
│ 6               ┆ PELO GESTOR POR DESATUALIZACAO… │
│ …               ┆ …                               │
│ 12              ┆ ALTERACAO DO REGIME DE DIREITO… │
│ 14              ┆ PELO GESTOR POR INCONSISTENCIA… │
│ 10              ┆ ENCERRAMENTO DAS ATIVIDADES     │
│ 11              ┆ MUDANCA DE MUNICIPIO            │
│ 13              ┆ ALTERACAO DE ATIVIDADE PRINCIP… │
└─────────────────┴─────────────────────────────────┘

In [40]:
dataframes['estabelecimento'].join(dataframes['cod_municipio'], left_on='CO_MUNICIPIO_GESTOR', right_on='CO_MUNICIPIO')

shape: (548_991, 68)
┌─────────────┬─────────┬────────────┬─────────┬───┬────────┬────────────┬────────────┬────────────┐
│ CO_UNIDADE  ┆ CO_CNES ┆ NU_CNPJ_MA ┆ TP_PFPJ ┆ … ┆ TP_MAC ┆ NU_POPULAC ┆ NU_DENSIDA ┆ CMTP_INICI │
│ ---         ┆ ---     ┆ NTENEDORA  ┆ ---     ┆   ┆ ---    ┆ AO         ┆ DE         ┆ O_MAC      │
│ i64         ┆ i64     ┆ ---        ┆ i64     ┆   ┆ str    ┆ ---        ┆ ---        ┆ ---        │
│             ┆         ┆ str        ┆         ┆   ┆        ┆ str        ┆ str        ┆ i64        │
╞═════════════╪═════════╪════════════╪═════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 26096025693 ┆ 2569302 ┆ 1040418400 ┆ 3       ┆ … ┆ S      ┆            ┆ 9          ┆ 32018      │
│ 02          ┆         ┆ 0109       ┆         ┆   ┆        ┆            ┆            ┆            │
│ 26096025719 ┆ 2571943 ┆ 1040418400 ┆ 3       ┆ … ┆ S      ┆            ┆ 9          ┆ 32018      │
│ 43          ┆         ┆ 0109       ┆         ┆   ┆        ┆            ┆            ┆            │
│ 26096023446 ┆ 2344637 ┆ 1040418400 ┆ 3       ┆ … ┆ S      ┆            ┆ 9          ┆ 32018      │
│ 37          ┆         ┆ 0109       ┆         ┆   ┆        ┆            ┆            ┆            │
│ 26096023446 ┆ 2344696 ┆ 1040418400 ┆ 3       ┆ … ┆ S      ┆            ┆ 9          ┆ 32018      │
│ 96          ┆         ┆ 0109       ┆         ┆   ┆        ┆            ┆            ┆            │
│ 31120021422 ┆ 2142295 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 95          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ …           ┆ …       ┆ …          ┆ …       ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 33045546516 ┆ 4651626 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆            ┆ 32018      │
│ 26          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 33045546590 ┆ 4659066 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆            ┆ 32018      │
│ 66          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 33045546610 ┆ 4661087 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆            ┆ 32018      │
│ 87          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 33045546641 ┆ 4664167 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆            ┆ 32018      │
│ 67          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
│ 35205046636 ┆ 4663640 ┆            ┆ 3       ┆ … ┆ S      ┆            ┆ 1          ┆ 32018      │
│ 40          ┆         ┆            ┆         ┆   ┆        ┆            ┆            ┆            │
└─────────────┴─────────┴────────────┴─────────┴───┴────────┴────────────┴────────────┴────────────┘

ComputeError: datatypes of join keys don't match - `CO_TIPO_ESTABELECIMENTO`: str on left does not match `CO_TIPO_ESTABELECIMENTO`: i64 on right

In [ ]:
tabelas = {
    'estabelecimento': 'tbEstabelecimento202409.csv',
    'tipo_estabelecimento': 'tbTipoEstabelecimento202409.csv',
    'atividade_principal': 'tbAtividade202409.csv',
    'natureza_juridica': 'tbNaturezaJuridica202409.csv',
    'motivo_desativacao': 'tbMotivoDesativacao202409.csv',
    'cod_municipio': 'tbMunicipio202409.csv'
}
file_path = "certeza_de_uso/BASE_DE_DADOS_CNES_202409/"


for var, tabela in tabelas

try:
    df = pl.read_csv(
        file_path,
        separator=';',                # Definir delimitador como ';'
        encoding='utf8-lossy',  # Tenta carregar com utf-8, ignorando caracteres problemáticos
        has_header=True,        # Assume que a primeira linha é o cabeçalho
        ignore_errors=True      # Ignora possíveis erros de parsing
    )
    print(df.head())
except Exception as e:
    print(f"Erro ao carregar o CSV: {e}")

shape: (5, 56)
┌────────────┬─────────┬────────────┬─────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ CO_UNIDADE ┆ CO_CNES ┆ NU_CNPJ_MA ┆ TP_PFPJ ┆ … ┆ CO_ATIVIDA ┆ ST_CONTRA ┆ CO_TIPO_A ┆ ST_COWORK │
│ ---        ┆ ---     ┆ NTENEDORA  ┆ ---     ┆   ┆ DE_PRINCIP ┆ TO_FORMAL ┆ BRANGENCI ┆ ING       │
│ i64        ┆ i64     ┆ ---        ┆ i64     ┆   ┆ AL         ┆ IZADO     ┆ A         ┆ ---       │
│            ┆         ┆ str        ┆         ┆   ┆ ---        ┆ ---       ┆ ---       ┆ str       │
│            ┆         ┆            ┆         ┆   ┆ str        ┆ str       ┆ str       ┆           │
╞════════════╪═════════╪════════════╪═════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2609602569 ┆ 2569302 ┆ 1040418400 ┆ 3       ┆ … ┆            ┆           ┆           ┆           │
│ 302        ┆         ┆ 0109       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 2609602571 ┆ 2571943 ┆ 1040418400 ┆ 3       ┆ … ┆ 001        ┆           ┆           ┆ N         │
│ 943        ┆         ┆ 0109       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 2609602344 ┆ 2344637 ┆ 1040418400 ┆ 3       ┆ … ┆ 012        ┆           ┆           ┆ N         │
│ 637        ┆         ┆ 0109       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 2609602344 ┆ 2344696 ┆ 1040418400 ┆ 3       ┆ … ┆ 012        ┆           ┆           ┆ N         │
│ 696        ┆         ┆ 0109       ┆         ┆   ┆            ┆           ┆           ┆           │
│ 3112002142 ┆ 2142295 ┆            ┆ 3       ┆ … ┆ 009        ┆ S         ┆           ┆           │
│ 295        ┆         ┆            ┆         ┆   ┆            ┆           ┆           ┆           │
└────────────┴─────────┴────────────┴─────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [24]:
for col in df.columns:
    print(df[col].value_counts(), '\n')

shape: (548_835, 2)
┌───────────────┬───────┐
│ CO_UNIDADE    ┆ count │
│ ---           ┆ ---   │
│ i64           ┆ u32   │
╞═══════════════╪═══════╡
│ 3543407007426 ┆ 1     │
│ 5103406584276 ┆ 1     │
│ 1504209970436 ┆ 1     │
│ 1709507343590 ┆ 1     │
│ 4310605257395 ┆ 1     │
│ …             ┆ …     │
│ 3503309834311 ┆ 1     │
│ 3550309602100 ┆ 1     │
│ 4209300890561 ┆ 1     │
│ 2210602884445 ┆ 1     │
│ 3554505051339 ┆ 1     │
└───────────────┴───────┘

shape: (548_991, 2)
┌─────────┬───────┐
│ CO_CNES ┆ count │
│ ---     ┆ ---   │
│ i64     ┆ u32   │
╞═════════╪═══════╡
│ 7616961 ┆ 1     │
│ 2286629 ┆ 1     │
│ 612561  ┆ 1     │
│ 5218152 ┆ 1     │
│ 6193501 ┆ 1     │
│ …       ┆ …     │
│ 2953757 ┆ 1     │
│ 7070012 ┆ 1     │
│ 4278518 ┆ 1     │
│ 3506908 ┆ 1     │
│ 6243045 ┆ 1     │
└─────────┴───────┘

shape: (7_264, 2)
┌─────────────────────┬───────┐
│ NU_CNPJ_MANTENEDORA ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ 80257355000108      ┆ 4     │
│ 01616255000146      ┆ 12    │
│ 12200168000120      ┆ 36    │
│ 07891682000119      ┆ 21    │
│ 27578434001525      ┆ 1     │
│ …                   ┆ …     │
│ 83102251000104      ┆ 27    │
│ 18641263000145      ┆ 3     │
│ 01612269000191      ┆ 4     │
│ 81076069000109      ┆ 1     │
│ 03963314000188      ┆ 1     │
└─────────────────────┴───────┘

shape: (2, 2)
┌─────────┬────────┐
│ TP_PFPJ ┆ count  │
│ ---     ┆ ---    │
│ i64     ┆ u32    │
╞═════════╪════════╡
│ 1       ┆ 160921 │
│ 3       ┆ 388070 │
└─────────┴────────┘

shape: (2, 2)
┌───────────┬────────┐
│ NIVEL_DEP ┆ count  │
│ ---       ┆ ---    │
│ i64       ┆ u32    │
╞═══════════╪════════╡
│ 3         ┆ 114037 │
│ 1         ┆ 434954 │
└───────────┴────────┘

shape: (413_223, 2)
┌─────────────────────────────────┬───────┐
│ NO_RAZAO_SOCIAL                 ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ ACOLHER CLINICA ESPECIALIZADA … ┆ 1     │
│ DERMOLIFE EIRELI LTDA           ┆ 1     │
│ EDINALDO ANTONIO MENDONCA       ┆ 1     │
│ FRANCINE ITALAMARA GOIZ VERA    ┆ 1     │
│ A A EVALDIR DA SILVA GANDUR FI… ┆ 1     │
│ …                               ┆ …     │
│ ANA M B L FERNANDES FISIOTERAP… ┆ 1     │
│ DRA MARIELLE PEREIRA ODONTOLOG… ┆ 1     │
│ GHETTI BAUERMANN SERVICOS ODON… ┆ 1     │
│ CLARISSA GIARETTA OLEKSINSKI    ┆ 1     │
│ OFTALMOCLIN CLINICA E CIRURGIA… ┆ 1     │
└─────────────────────────────────┴───────┘

shape: (474_311, 2)
┌─────────────────────────────────┬───────┐
│ NO_FANTASIA                     ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ VITALE                          ┆ 7     │
│ CONS MEDICO YARA MARIA DA SILV… ┆ 1     │
│ UNICLINICA ASSISTENCIA MEDICA … ┆ 1     │
│ MARCOS ANTONIO STUDART GURGEL … ┆ 1     │
│ EDILSON LUIZ MIGLIORINI MARAU   ┆ 1     │
│ …                               ┆ …     │
│ JOSE ODENIR DALMASCHIO          ┆ 1     │
│ CEMA HOSPITAL ESPECIALIZADO     ┆ 1     │
│ FUNDACAO DR NELSON MEIRELES     ┆ 1     │
│ INSTITUTO DE IMAGEM DE PAULO A… ┆ 1     │
│ SMS DE COCAL DE TELHA           ┆ 1     │
└─────────────────────────────────┴───────┘

shape: (173_901, 2)
┌─────────────────────────────────┬───────┐
│ NO_LOGRADOURO                   ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ SANTANA                         ┆ 104   │
│ DA UNIVERSIDADE                 ┆ 4     │
│ AVENIDA NICOLA DE BAPTISTA NET… ┆ 1     │
│ RUA PLACIDO DE CASTRO           ┆ 21    │
│ R MAURICIO                      ┆ 1     │
│ …                               ┆ …     │
│ CEL ANTONIO INACIO              ┆ 1     │
│ POVOADO DE QUATRO BOCAS         ┆ 1     │
│ AVENIDA BERNARDO BEZERRA        ┆ 1     │
│ RUA PADRE NICOLAU PIMENTEL      ┆ 1     │
│ AVENIDA COUTOS                  ┆ 1     │
└─────────────────────────────────┴───────┘

shape: (8_619, 2)
┌─────────────┬───────┐
│ NU_ENDERECO ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ 4326        ┆ 5     │
│ 4334        ┆ 2     │
│ 1544        ┆ 27    │
│ 3476        ┆ 3     │
│ 11469       ┆ 1     │
│ …           ┆ …     │
│ 6517        ┆ 1     │
│ 1115        ┆ 173   │
│ 3641        ┆ 3     │
│ 16080       ┆ 1     │
│ 9621        ┆ 1     │
└─────────────┴───────┘

shape: (68_993, 2)
┌──────────────────────┬───────┐
│ NO_COMPLEMENTO       ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ SALA 1323            ┆ 4     │
│ EDIF HC PLAZAR       ┆ 1     │
│ BLOCO B SALA 310     ┆ 2     │
│ ANTIGO SESC          ┆ 6     │
│ SALA 204 ANDAR 02 BL ┆ 1     │
│ …                    ┆ …     │
│ SL 329 ED SANTA MARI ┆ 1     │
│ SALA 1201 12ANDAR    ┆ 1     │
│ LOJA 0110            ┆ 3     │
│ LOJA 67 E 71         ┆ 1     │
│ SALAS 1204 E 1205    ┆ 5     │
└──────────────────────┴───────┘

shape: (35_353, 2)
┌──────────────────────┬───────┐
│ NO_BAIRRO            ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ TAMBAUZINHO          ┆ 142   │
│ DEBRASA              ┆ 1     │
│ FLORESTAL            ┆ 52    │
│ MINI PARQUE INDUSTRI ┆ 1     │
│ JARDIM DAS PEDRAS    ┆ 1     │
│ …                    ┆ …     │
│ APRAZIVEL            ┆ 1     │
│ TRES VENDAS          ┆ 169   │
│ VILA SAO ROQUE       ┆ 3     │
│ DONGA MICHILES       ┆ 1     │
│ VILA ROSA            ┆ 79    │
└──────────────────────┴───────┘

shape: (100_809, 2)
┌──────────┬───────┐
│ CO_CEP   ┆ count │
│ ---      ┆ ---   │
│ i64      ┆ u32   │
╞══════════╪═══════╡
│ 11310060 ┆ 16    │
│ 50670010 ┆ 1     │
│ 32600110 ┆ 2     │
│ 37274970 ┆ 1     │
│ 85601640 ┆ 1     │
│ …        ┆ …     │
│ 76803884 ┆ 6     │
│ 11706210 ┆ 1     │
│ 55660000 ┆ 106   │
│ 79603120 ┆ 1     │
│ 5414901  ┆ 21    │
└──────────┴───────┘

shape: (917, 2)
┌─────────────────┬───────┐
│ CO_REGIAO_SAUDE ┆ count │
│ ---             ┆ ---   │
│ str             ┆ u32   │
╞═════════════════╪═══════╡
│ 5� R            ┆ 2     │
│ 33              ┆ 90    │
│ SSO             ┆ 1     │
│ 3545            ┆ 1     │
│ 5A              ┆ 10    │
│ …               ┆ …     │
│ 1A.             ┆ 1     │
│ 066             ┆ 1     │
│ 7CR             ┆ 25    │
│ RSCS            ┆ 1     │
│ 3501            ┆ 8     │
└─────────────────┴───────┘

shape: (1, 2)
┌─────────────────┬────────┐
│ CO_MICRO_REGIAO ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u32    │
╞═════════════════╪════════╡
│                 ┆ 548991 │
└─────────────────┴────────┘

shape: (139, 2)
┌───────────────────────┬───────┐
│ CO_DISTRITO_SANITARIO ┆ count │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ 21                    ┆ 261   │
│ 5096                  ┆ 1     │
│ 9901                  ┆ 297   │
│ 006                   ┆ 57    │
│ 9929                  ┆ 2     │
│ …                     ┆ …     │
│ 0110                  ┆ 36    │
│ 9917                  ┆ 8     │
│ 6811                  ┆ 1     │
│ 4194                  ┆ 1     │
│ 0180                  ┆ 416   │
└───────────────────────┴───────┘

shape: (161, 2)
┌────────────────────────────┬───────┐
│ CO_DISTRITO_ADMINISTRATIVO ┆ count │
│ ---                        ┆ ---   │
│ str                        ┆ u32   │
╞════════════════════════════╪═══════╡
│ 0009                       ┆ 1     │
│ 0028                       ┆ 2     │
│ 0042                       ┆ 1     │
│ 0069                       ┆ 3     │
│ 000                        ┆ 49    │
│ …                          ┆ …     │
│ 1                          ┆ 413   │
│ Q                          ┆ 1     │
│ 092                        ┆ 3     │
│ 004                        ┆ 1     │
│ --                         ┆ 1     │
└────────────────────────────┴───────┘

shape: (364_082, 2)
┌───────────────┬───────┐
│ NU_TELEFONE   ┆ count │
│ ---           ┆ ---   │
│ str           ┆ u32   │
╞═══════════════╪═══════╡
│ 19 3405 2253  ┆ 1     │
│ 2179831350    ┆ 1     │
│ 17-996311313  ┆ 1     │
│ 67 33258081   ┆ 1     │
│ 42 91249661   ┆ 1     │
│ …             ┆ …     │
│ 11-2691-6975  ┆ 2     │
│ 69 92422134   ┆ 1     │
│ 61 35416756   ┆ 1     │
│ 5499800015    ┆ 1     │
│ 64 9 92993663 ┆ 1     │
└───────────────┴───────┘

shape: (1, 2)
┌────────┬────────┐
│ NU_FAX ┆ count  │
│ ---    ┆ ---    │
│ str    ┆ u32    │
╞════════╪════════╡
│        ┆ 548991 │
└────────┴────────┘

shape: (235_023, 2)
┌─────────────────────────────────┬───────┐
│ NO_EMAIL                        ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ veronicagomes.angra@gmail.com   ┆ 1     │
│ deborahbrazuna@gmail.com        ┆ 1     │
│ PKR.BAZAR@GMAIL.COM             ┆ 1     │
│ institutomarcondes@hotmail.com  ┆ 1     │
│ thiago.castelar@hotmail.com     ┆ 1     │
│ …                               ┆ …     │
│ pediatria@saojosedoriopardo.sp… ┆ 1     │
│ kathielly_s2@hotmail.com        ┆ 1     │
│ THAIROBULKOOL1@GMAIL.COM        ┆ 1     │
│ carlosbichuetti@gmail.com       ┆ 1     │
│ cont.comercial1404@gmail.com    ┆ 1     │
└─────────────────────────────────┴───────┘

shape: (153_366, 2)
┌─────────────┬───────┐
│ NU_CPF      ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ 07045913591 ┆ 1     │
│ 54009936649 ┆ 1     │
│ 58578293649 ┆ 1     │
│ 15431592068 ┆ 1     │
│ 31216846634 ┆ 1     │
│ …           ┆ …     │
│ 09769227897 ┆ 1     │
│ 03430448468 ┆ 1     │
│ 25490060620 ┆ 1     │
│ 07067579716 ┆ 1     │
│ 04369200180 ┆ 1     │
└─────────────┴───────┘

shape: (273_284, 2)
┌────────────────┬───────┐
│ NU_CNPJ        ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ 01313540000198 ┆ 2     │
│ 89890172000191 ┆ 1     │
│ 53213682000187 ┆ 2     │
│ 41054153000107 ┆ 1     │
│ 48208818000120 ┆ 1     │
│ …              ┆ …     │
│ 44649812018185 ┆ 1     │
│ 07691218000189 ┆ 1     │
│ 13255299000177 ┆ 1     │
│ 21849698000194 ┆ 1     │
│ 32172490000108 ┆ 1     │
└────────────────┴───────┘

shape: (5, 2)
┌──────────────┬────────┐
│ CO_ATIVIDADE ┆ count  │
│ ---          ┆ ---    │
│ i64          ┆ u32    │
╞══════════════╪════════╡
│ 1            ┆ 1255   │
│ 2            ┆ 773    │
│ 3            ┆ 5461   │
│ 4            ┆ 541321 │
│ 5            ┆ 181    │
└──────────────┴────────┘

shape: (4, 2)
┌──────────────┬────────┐
│ CO_CLIENTELA ┆ count  │
│ ---          ┆ ---    │
│ i64          ┆ u32    │
╞══════════════╪════════╡
│ null         ┆ 7673   │
│ 3            ┆ 293793 │
│ 1            ┆ 211645 │
│ 2            ┆ 35880  │
└──────────────┴────────┘

shape: (290_717, 2)
┌──────────────────────────┬───────┐
│ NU_ALVARA                ┆ count │
│ ---                      ┆ ---   │
│ str                      ┆ u32   │
╞══════════════════════════╪═══════╡
│ 352730601-863-000217-1-7 ┆ 1     │
│ 2000225/2020             ┆ 1     │
│ 3436                     ┆ 2     │
│ 6018.2018/0026207-2      ┆ 1     │
│ 07.01372.2.05            ┆ 1     │
│ …                        ┆ …     │
│ 219471                   ┆ 1     │
│ 1733/2021                ┆ 1     │
│ 2021088811               ┆ 1     │
│ 2280/2015                ┆ 1     │
│ 033/2007                 ┆ 2     │
└──────────────────────────┴───────┘

shape: (11_749, 2)
┌──────────────────────┬───────┐
│ DT_EXPEDICAO         ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 23-mai-1990 00:00:00 ┆ 2     │
│ 30-jan-2017 00:00:00 ┆ 55    │
│ 02-jan-1985 00:00:00 ┆ 4     │
│ 13-abr-2022 00:00:00 ┆ 148   │
│ 19-jun-2005 00:00:00 ┆ 3     │
│ …                    ┆ …     │
│ 26-ago-2015 00:00:00 ┆ 37    │
│ 12-jul-2003 00:00:00 ┆ 2     │
│ 17-dez-2001 00:00:00 ┆ 9     │
│ 09-ago-2001 00:00:00 ┆ 21    │
│ 08-mar-2006 00:00:00 ┆ 53    │
└──────────────────────┴───────┘

shape: (4, 2)
┌────────────────────┬────────┐
│ TP_ORGAO_EXPEDIDOR ┆ count  │
│ ---                ┆ ---    │
│ str                ┆ u32    │
╞════════════════════╪════════╡
│                    ┆ 170867 │
│ 3                  ┆ 2      │
│ 1                  ┆ 30978  │
│ 2                  ┆ 347144 │
└────────────────────┴────────┘

shape: (9_943, 2)
┌──────────────────────┬───────┐
│ DT_VAL_LIC_SANI      ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ 17-mai-2023 00:00:00 ┆ 77    │
│ 30-out-2008 00:00:00 ┆ 1     │
│ 01-jan-2031 00:00:00 ┆ 2     │
│ 03-ago-2023 00:00:00 ┆ 80    │
│ 14-out-2020 00:00:00 ┆ 46    │
│ …                    ┆ …     │
│ 08-fev-2027 00:00:00 ┆ 14    │
│ 08-set-2009 00:00:00 ┆ 1     │
│ 23-jul-2025 00:00:00 ┆ 36    │
│ 22-jun-2006 00:00:00 ┆ 3     │
│ 23-fev-2029 00:00:00 ┆ 4     │
└──────────────────────┴───────┘

shape: (3, 2)
┌─────────────┬────────┐
│ TP_LIC_SANI ┆ count  │
│ ---         ┆ ---    │
│ str         ┆ u32    │
╞═════════════╪════════╡
│ 1           ┆ 201139 │
│             ┆ 328210 │
│ 2           ┆ 19642  │
└─────────────┴────────┘

shape: (39, 2)
┌────────────┬───────┐
│ TP_UNIDADE ┆ count │
│ ---        ┆ ---   │
│ i64        ┆ u32   │
╞════════════╪═══════╡
│ 84         ┆ 1923  │
│ 62         ┆ 1102  │
│ 21         ┆ 124   │
│ 78         ┆ 109   │
│ 68         ┆ 6571  │
│ …          ┆ …     │
│ 36         ┆ 94662 │
│ 75         ┆ 290   │
│ 67         ┆ 31    │
│ 77         ┆ 1899  │
│ 85         ┆ 1012  │
└────────────┴───────┘

shape: (8, 2)
┌──────────────────────┬────────┐
│ CO_TURNO_ATENDIMENTO ┆ count  │
│ ---                  ┆ ---    │
│ i64                  ┆ u32    │
╞══════════════════════╪════════╡
│ 4                    ┆ 64081  │
│ 3                    ┆ 420557 │
│ null                 ┆ 1679   │
│ 5                    ┆ 9673   │
│ 2                    ┆ 16729  │
│ 7                    ┆ 1098   │
│ 6                    ┆ 24508  │
│ 1                    ┆ 10666  │
└──────────────────────┴────────┘

shape: (27, 2)
┌──────────────────┬────────┐
│ CO_ESTADO_GESTOR ┆ count  │
│ ---              ┆ ---    │
│ i64              ┆ u32    │
╞══════════════════╪════════╡
│ 23               ┆ 17115  │
│ 28               ┆ 5175   │
│ 35               ┆ 133518 │
│ 32               ┆ 11681  │
│ 15               ┆ 10883  │
│ …                ┆ …      │
│ 11               ┆ 6007   │
│ 27               ┆ 4943   │
│ 33               ┆ 49962  │
│ 22               ┆ 5803   │
│ 42               ┆ 30363  │
└──────────────────┴────────┘

shape: (5_584, 2)
┌─────────────────────┬───────┐
│ CO_MUNICIPIO_GESTOR ┆ count │
│ ---                 ┆ ---   │
│ i64                 ┆ u32   │
╞═════════════════════╪═══════╡
│ 510558              ┆ 23    │
│ 290540              ┆ 21    │
│ 521390              ┆ 10    │
│ 315690              ┆ 95    │
│ 410180              ┆ 246   │
│ …                   ┆ …     │
│ 292550              ┆ 44    │
│ 431177              ┆ 9     │
│ 350275              ┆ 31    │
│ 250490              ┆ 15    │
│ 311580              ┆ 17    │
└─────────────────────┴───────┘

shape: (6_277, 2)
┌─────────────────────────────────┬───────┐
│ TO_CHAR(DT_ATUALIZACAO,'DD/MM/… ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ 23/02/2016                      ┆ 14    │
│ 19/11/2015                      ┆ 16    │
│ 19/05/2024                      ┆ 36    │
│ 12/04/2015                      ┆ 2     │
│ 07/05/2008                      ┆ 8     │
│ …                               ┆ …     │
│ 18/08/2022                      ┆ 386   │
│ 11/07/2019                      ┆ 508   │
│ 01/10/2018                      ┆ 7     │
│ 14/04/2010                      ┆ 15    │
│ 06/07/2004                      ┆ 8     │
└─────────────────────────────────┴───────┘

shape: (8_197, 2)
┌─────────────┬───────┐
│ CO_USUARIO  ┆ count │
│ ---         ┆ ---   │
│ str         ┆ u32   │
╞═════════════╪═══════╡
│ FIEL LAB    ┆ 1     │
│ YASMIM      ┆ 11    │
│ DAYANARA    ┆ 3     │
│ TGRANDE     ┆ 4     │
│ WLADIMIR    ┆ 160   │
│ …           ┆ …     │
│ RUBENSCNJR  ┆ 1     │
│ CRISPANI    ┆ 155   │
│ PFLCONTABIL ┆ 2     │
│ ROMANO      ┆ 11    │
│ 9373609     ┆ 1     │
└─────────────┴───────┘

shape: (429_951, 2)
┌──────────────────┬───────┐
│ CO_CPFDIRETORCLN ┆ count │
│ ---              ┆ ---   │
│ str              ┆ u32   │
╞══════════════════╪═══════╡
│ 60128208791      ┆ 1     │
│ 28149660810      ┆ 1     │
│ 30471940410      ┆ 1     │
│ 52905144653      ┆ 1     │
│ 07308812618      ┆ 2     │
│ …                ┆ …     │
│ 02811690980      ┆ 1     │
│ 04028756995      ┆ 1     │
│ 76335925320      ┆ 1     │
│ 06497209620      ┆ 1     │
│ 94666750100      ┆ 1     │
└──────────────────┴───────┘

shape: (167_644, 2)
┌────────────────┬───────┐
│ REG_DIRETORCLN ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ 61118492       ┆ 1     │
│ 10083-TO       ┆ 1     │
│ 586184         ┆ 1     │
│ 789662         ┆ 1     │
│ 31625          ┆ 4     │
│ …              ┆ …     │
│ 041898         ┆ 1     │
│ 302309         ┆ 1     │
│ 0430884        ┆ 1     │
│ 196117         ┆ 1     │
│ 57724          ┆ 1     │
└────────────────┴───────┘

shape: (4, 2)
┌─────────────────────┬────────┐
│ ST_ADESAO_FILANTROP ┆ count  │
│ ---                 ┆ ---    │
│ str                 ┆ u32    │
╞═════════════════════╪════════╡
│ 1                   ┆ 628    │
│                     ┆ 546390 │
│ 2                   ┆ 1427   │
│                     ┆ 546    │
└─────────────────────┴────────┘

shape: (15, 2)
┌─────────────────┬────────┐
│ CO_MOTIVO_DESAB ┆ count  │
│ ---             ┆ ---    │
│ str             ┆ u32    │
╞═════════════════╪════════╡
│ 04              ┆ 30324  │
│ 14              ┆ 74     │
│ 12              ┆ 23     │
│ 05              ┆ 39     │
│ 06              ┆ 13260  │
│ …               ┆ …      │
│ 13              ┆ 310    │
│ 10              ┆ 19754  │
│ 09              ┆ 87     │
│                 ┆ 438998 │
│ 07              ┆ 1793   │
└─────────────────┴────────┘

shape: (7_903, 2)
┌─────────────────────────────────┬───────┐
│ NO_URL                          ┆ count │
│ ---                             ┆ ---   │
│ str                             ┆ u32   │
╞═════════════════════════════════╪═══════╡
│ SOCIETARIO@SINALLACONTABILIDAD… ┆ 1     │
│ www.orthodonticbrasil.com.br    ┆ 1     │
│ rh@pat.com.br                   ┆ 1     │
│ www.gestiss.com.br              ┆ 1     │
│ patriciadupas84@gmail.com       ┆ 1     │
│ …                               ┆ …     │
│ www.ivoneoftalmologia.com.br    ┆ 1     │
│ legalizacao@escritorioaurora.c… ┆ 2     │
│ https://www.casadecaridade.com… ┆ 1     │
│ dracarolina8709@gmail.com       ┆ 1     │
│ www.saudepulmonar.com.br        ┆ 1     │
└─────────────────────────────────┴───────┘

shape: (278_415, 2)
┌─────────────────────┬───────┐
│ NU_LATITUDE         ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ -18.169834467347126 ┆ 1     │
│ -23.6526594         ┆ 1     │
│ -17.220884          ┆ 1     │
│ -13.068505009453988 ┆ 1     │
│ -22.530111          ┆ 2     │
│ …                   ┆ …     │
│ -20.3182539         ┆ 1     │
│ -7.1475877          ┆ 1     │
│ -23.160             ┆ 4     │
│ -21.7420601         ┆ 1     │
│ -20.953865196903163 ┆ 1     │
└─────────────────────┴───────┘

shape: (277_508, 2)
┌─────────────────────┬───────┐
│ NU_LONGITUDE        ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ -42.5335138         ┆ 1     │
│ -44.411             ┆ 3     │
│ -46.16755485534668  ┆ 1     │
│ -48.6752047         ┆ 3     │
│ -38.506537          ┆ 1     │

In [10]:
df.group_by(
    pl.col('CO_UNIDADE')
).agg(
    pl.col('NO_RAZAO_SOCIAL').n_unique(),
    pl.col('NO_FANTASIA').n_unique()
).filter(
    pl.col('NO_RAZAO_SOCIAL') > 1
)

shape: (1, 3)
┌────────────┬─────────────────┬─────────────┐
│ CO_UNIDADE ┆ NO_RAZAO_SOCIAL ┆ NO_FANTASIA │
│ ---        ┆ ---             ┆ ---         │
│ i64        ┆ u32             ┆ u32         │
╞════════════╪═════════════════╪═════════════╡
│ null       ┆ 135             ┆ 155         │
└────────────┴─────────────────┴─────────────┘